// ═══════════════════════════════════════════════════════
//  database.js — 200+ Real FUT Stars & Legends Database
// ═══════════════════════════════════════════════════════

export const PLAYERS = [
  // ── LEGENDS (Icons) ──────────────────────────────────
  { id:1,   name:"L. Messi",       pos:"ATT", ovr:93, club:"Inter Miami",    nat:"Argentina",  cardType:"legend",  flag:"🇦🇷", faceUrl:"https://cdn.sofifa.net/players/158/023/25_120.png" },
  { id:2,   name:"C. Ronaldo",     pos:"ATT", ovr:91, club:"Al Nassr",       nat:"Portugal",   cardType:"legend",  flag:"🇵🇹", faceUrl:"https://cdn.sofifa.net/players/020/801/25_120.png" },
  { id:3,   name:"Pelé",           pos:"ATT", ovr:98, club:"Santos (Icon)",  nat:"Brazil",     cardType:"legend",  flag:"🇧🇷", faceUrl:"https://cdn.sofifa.net/players/102/823/25_120.png" },
  { id:4,   name:"Maradona",       pos:"ATT", ovr:97, club:"Napoli (Icon)",  nat:"Argentina",  cardType:"legend",  flag:"🇦🇷", faceUrl:"https://cdn.sofifa.net/players/102/872/25_120.png" },
  { id:5,   name:"Ronaldinho",     pos:"ATT", ovr:96, club:"Barcelona (I)",  nat:"Brazil",     cardType:"legend",  flag:"🇧🇷", faceUrl:"https://cdn.sofifa.net/players/131/976/25_120.png" },
  { id:6,   name:"Zidane",         pos:"MID", ovr:96, club:"Real Madrid (I)",nat:"France",     cardType:"legend",  flag:"🇫🇷", faceUrl:"https://cdn.sofifa.net/players/101/669/25_120.png" },
  { id:7,   name:"Cruyff",         pos:"ATT", ovr:97, club:"Ajax (Icon)",    nat:"Netherlands",cardType:"legend",  flag:"🇳🇱", faceUrl:"https://cdn.sofifa.net/players/102/824/25_120.png" },
  { id:8,   name:"Ronaldo R9",     pos:"ATT", ovr:97, club:"Real Madrid (I)",nat:"Brazil",     cardType:"legend",  flag:"🇧🇷", faceUrl:"https://cdn.sofifa.net/players/102/820/25_120.png" },
  { id:9,   name:"Maldini",        pos:"DEF", ovr:96, club:"AC Milan (Icon)",nat:"Italy",      cardType:"legend",  flag:"🇮🇹", faceUrl:"https://cdn.sofifa.net/players/102/879/25_120.png" },
  { id:10,  name:"Buffon",         pos:"GK",  ovr:91, club:"Juventus (Icon)",nat:"Italy",      cardType:"legend",  flag:"🇮🇹", faceUrl:"https://cdn.sofifa.net/players/152/040/25_120.png" },
  { id:11,  name:"Yashin",         pos:"GK",  ovr:95, club:"Dynamo (Icon)", nat:"USSR",        cardType:"legend",  flag:"🇷🇺", faceUrl:"https://cdn.sofifa.net/players/102/825/25_120.png" },
  { id:12,  name:"Beckham",        pos:"MID", ovr:92, club:"Man Utd (Icon)", nat:"England",    cardType:"legend",  flag:"🏴󠁧󠁢󠁥󠁮󠁧󠁿", faceUrl:"https://cdn.sofifa.net/players/152/048/25_120.png" },
  { id:13,  name:"Henry",          pos:"ATT", ovr:95, club:"Arsenal (Icon)", nat:"France",     cardType:"legend",  flag:"🇫🇷", faceUrl:"https://cdn.sofifa.net/players/145/715/25_120.png" },
  { id:14,  name:"Shevchenko",     pos:"ATT", ovr:91, club:"AC Milan (Icon)",nat:"Ukraine",    cardType:"legend",  flag:"🇺🇦", faceUrl:"https://cdn.sofifa.net/players/152/050/25_120.png" },
  { id:15,  name:"Gerrard",        pos:"MID", ovr:91, club:"Liverpool (I)",  nat:"England",    cardType:"legend",  flag:"🏴󠁧󠁢󠁥󠁮󠁧󠁿", faceUrl:"https://cdn.sofifa.net/players/152/476/25_120.png" },
  { id:16,  name:"Lampard",        pos:"MID", ovr:91, club:"Chelsea (Icon)", nat:"England",    cardType:"legend",  flag:"🏴󠁧󠁢󠁥󠁮󠁧󠁿", faceUrl:"https://cdn.sofifa.net/players/152/511/25_120.png" },
  { id:17,  name:"Pirlo",          pos:"MID", ovr:92, club:"Juventus (I)",   nat:"Italy",      cardType:"legend",  flag:"🇮🇹", faceUrl:"https://cdn.sofifa.net/players/162/649/25_120.png" },
  { id:18,  name:"Xavi",           pos:"MID", ovr:92, club:"Barcelona (I)",  nat:"Spain",      cardType:"legend",  flag:"🇪🇸", faceUrl:"https://cdn.sofifa.net/players/152/547/25_120.png" },
  { id:19,  name:"Iniesta",        pos:"MID", ovr:91, club:"Barcelona (I)",  nat:"Spain",      cardType:"legend",  flag:"🇪🇸", faceUrl:"https://cdn.sofifa.net/players/159/212/25_120.png" },
  { id:20,  name:"Cafu",           pos:"DEF", ovr:90, club:"AC Milan (Icon)",nat:"Brazil",     cardType:"legend",  flag:"🇧🇷", faceUrl:"https://cdn.sofifa.net/players/102/818/25_120.png" },
  { id:21,  name:"R. Carlos",      pos:"DEF", ovr:92, club:"Real Madrid (I)",nat:"Brazil",     cardType:"legend",  flag:"🇧🇷", faceUrl:"https://cdn.sofifa.net/players/102/819/25_120.png" },
  { id:22,  name:"Cantona",        pos:"ATT", ovr:91, club:"Man Utd (Icon)", nat:"France",     cardType:"legend",  flag:"🇫🇷", faceUrl:"https://cdn.sofifa.net/players/102/826/25_120.png" },
  { id:23,  name:"Nedvěd",         pos:"MID", ovr:90, club:"Juventus (I)",   nat:"Czech Rep.", cardType:"legend",  flag:"🇨🇿", faceUrl:"https://cdn.sofifa.net/players/152/044/25_120.png" },
  { id:24,  name:"Totti",          pos:"ATT", ovr:91, club:"Roma (Icon)",    nat:"Italy",      cardType:"legend",  flag:"🇮🇹", faceUrl:"https://cdn.sofifa.net/players/152/012/25_120.png" },
  { id:25,  name:"Van Basten",     pos:"ATT", ovr:96, club:"AC Milan (Icon)",nat:"Netherlands",cardType:"legend",  flag:"🇳🇱", faceUrl:"https://cdn.sofifa.net/players/102/833/25_120.png" },

  // ── SPECIAL / TOTY ─────────────────────────────────
  { id:26,  name:"K. Mbappé",      pos:"ATT", ovr:91, club:"Real Madrid",    nat:"France",     cardType:"special", flag:"🇫🇷", faceUrl:"https://cdn.sofifa.net/players/231/747/25_120.png" },
  { id:27,  name:"E. Haaland",     pos:"ATT", ovr:91, club:"Man City",       nat:"Norway",     cardType:"special", flag:"🇳🇴", faceUrl:"https://cdn.sofifa.net/players/239/085/25_120.png" },
  { id:28,  name:"V. Junior",      pos:"ATT", ovr:90, club:"Real Madrid",    nat:"Brazil",     cardType:"special", flag:"🇧🇷", faceUrl:"https://cdn.sofifa.net/players/254/530/25_120.png" },
  { id:29,  name:"J. Bellingham",  pos:"MID", ovr:90, club:"Real Madrid",    nat:"England",    cardType:"special", flag:"🏴󠁧󠁢󠁥󠁮󠁧󠁿", faceUrl:"https://cdn.sofifa.net/players/256/560/25_120.png" },
  { id:30,  name:"L. Yamal",       pos:"ATT", ovr:84, club:"Barcelona",      nat:"Spain",      cardType:"special", flag:"🇪🇸", faceUrl:"https://cdn.sofifa.net/players/278/603/25_120.png" },
  { id:31,  name:"R. Leão",        pos:"ATT", ovr:87, club:"AC Milan",       nat:"Portugal",   cardType:"special", flag:"🇵🇹", faceUrl:"https://cdn.sofifa.net/players/246/432/25_120.png" },
  { id:32,  name:"F. de Jong",     pos:"MID", ovr:86, club:"Barcelona",      nat:"Netherlands",cardType:"special", flag:"🇳🇱", faceUrl:"https://cdn.sofifa.net/players/240/249/25_120.png" },
  { id:33,  name:"P. Dybala",      pos:"ATT", ovr:87, club:"AS Roma",        nat:"Argentina",  cardType:"special", flag:"🇦🇷", faceUrl:"https://cdn.sofifa.net/players/209/331/25_120.png" },
  { id:34,  name:"K. Benzema",     pos:"ATT", ovr:89, club:"Al-Ittihad",     nat:"France",     cardType:"special", flag:"🇫🇷", faceUrl:"https://cdn.sofifa.net/players/182/521/25_120.png" },
  { id:35,  name:"N. Barella",     pos:"MID", ovr:87, club:"Inter Milan",    nat:"Italy",      cardType:"special", flag:"🇮🇹", faceUrl:"https://cdn.sofifa.net/players/239/704/25_120.png" },
  { id:36,  name:"M. Salah",       pos:"ATT", ovr:89, club:"Liverpool",      nat:"Egypt",      cardType:"special", flag:"🇪🇬", faceUrl:"https://cdn.sofifa.net/players/209/331/25_120.png" },
  { id:37,  name:"Son Heung-min",  pos:"ATT", ovr:87, club:"Tottenham",      nat:"S. Korea",   cardType:"special", flag:"🇰🇷", faceUrl:"https://cdn.sofifa.net/players/202/126/25_120.png" },

  // ── GOLD GKs ───────────────────────────────────────
  { id:40,  name:"T. Courtois",    pos:"GK",  ovr:91, club:"Real Madrid",    nat:"Belgium",    cardType:"gold",    flag:"🇧🇪", faceUrl:"https://cdn.sofifa.net/players/200/389/25_120.png" },
  { id:41,  name:"Alisson",        pos:"GK",  ovr:90, club:"Liverpool",      nat:"Brazil",     cardType:"gold",    flag:"🇧🇷", faceUrl:"https://cdn.sofifa.net/players/212/831/25_120.png" },
  { id:42,  name:"M. ter Stegen",  pos:"GK",  ovr:89, club:"Barcelona",      nat:"Germany",    cardType:"gold",    flag:"🇩🇪", faceUrl:"https://cdn.sofifa.net/players/192/448/25_120.png" },
  { id:43,  name:"E. Martínez",    pos:"GK",  ovr:89, club:"Aston Villa",    nat:"Argentina",  cardType:"gold",    flag:"🇦🇷", faceUrl:"https://cdn.sofifa.net/players/222/419/25_120.png" },
  { id:44,  name:"K. Navas",       pos:"GK",  ovr:86, club:"Nottm Forest",   nat:"Costa Rica", cardType:"gold",    flag:"🇨🇷", faceUrl:"https://cdn.sofifa.net/players/185/314/25_120.png" },
  { id:45,  name:"M. Neuer",       pos:"GK",  ovr:88, club:"Bayern Munich",  nat:"Germany",    cardType:"gold",    flag:"🇩🇪", faceUrl:"https://cdn.sofifa.net/players/167/495/25_120.png" },
  { id:46,  name:"J. Oblak",       pos:"GK",  ovr:89, club:"Atlético Madrid",nat:"Slovenia",   cardType:"gold",    flag:"🇸🇮", faceUrl:"https://cdn.sofifa.net/players/200/622/25_120.png" },
  { id:47,  name:"G. Donnarumma",  pos:"GK",  ovr:88, club:"PSG",           nat:"Italy",      cardType:"gold",    flag:"🇮🇹", faceUrl:"https://cdn.sofifa.net/players/238/194/25_120.png" },
  { id:48,  name:"D. Maignan",     pos:"GK",  ovr:87, club:"AC Milan",       nat:"France",     cardType:"gold",    flag:"🇫🇷", faceUrl:"https://cdn.sofifa.net/players/218/729/25_120.png" },
  { id:49,  name:"S. Mandanda",    pos:"GK",  ovr:82, club:"Stade Rennais",  nat:"France",     cardType:"silver",  flag:"🇫🇷", faceUrl:"https://cdn.sofifa.net/players/172/921/25_120.png" },

  // ── GOLD DEFs ──────────────────────────────────────
  { id:60,  name:"V. van Dijk",    pos:"DEF", ovr:90, club:"Liverpool",      nat:"Netherlands",cardType:"gold",    flag:"🇳🇱", faceUrl:"https://cdn.sofifa.net/players/203/376/25_120.png" },
  { id:61,  name:"K. Rüdiger",     pos:"DEF", ovr:86, club:"Real Madrid",    nat:"Germany",    cardType:"gold",    flag:"🇩🇪", faceUrl:"https://cdn.sofifa.net/players/198/779/25_120.png" },
  { id:62,  name:"W. Saliba",      pos:"DEF", ovr:87, club:"Arsenal",        nat:"France",     cardType:"gold",    flag:"🇫🇷", faceUrl:"https://cdn.sofifa.net/players/263/634/25_120.png" },
  { id:63,  name:"T. Hernández",   pos:"DEF", ovr:86, club:"AC Milan",       nat:"France",     cardType:"gold",    flag:"🇫🇷", faceUrl:"https://cdn.sofifa.net/players/241/983/25_120.png" },
  { id:64,  name:"João Cancelo",   pos:"DEF", ovr:85, club:"Barcelona",      nat:"Portugal",   cardType:"gold",    flag:"🇵🇹", faceUrl:"https://cdn.sofifa.net/players/210,054/25_120.png" },
  { id:65,  name:"A. Robertson",   pos:"DEF", ovr:86, club:"Liverpool",      nat:"Scotland",   cardType:"gold",    flag:"🏴󠁧󠁢󠁳󠁣󠁴󠁿", faceUrl:"https://cdn.sofifa.net/players/208,110/25_120.png" },
  { id:66,  name:"R. Carvajal",    pos:"DEF", ovr:86, club:"Real Madrid",    nat:"Spain",      cardType:"gold",    flag:"🇪🇸", faceUrl:"https://cdn.sofifa.net/players/195,865/25_120.png" },
  { id:67,  name:"L. Hernández",   pos:"DEF", ovr:85, club:"Atlético Madrid",nat:"France",     cardType:"gold",    flag:"🇫🇷", faceUrl:"https://cdn.sofifa.net/players/213,157/25_120.png" },
  { id:68,  name:"B. Pavard",      pos:"DEF", ovr:84, club:"Inter Milan",    nat:"France",     cardType:"gold",    flag:"🇫🇷", faceUrl:"https://cdn.sofifa.net/players/233,024/25_120.png" },
  { id:69,  name:"A. Bastoni",     pos:"DEF", ovr:86, club:"Inter Milan",    nat:"Italy",      cardType:"gold",    flag:"🇮🇹", faceUrl:"https://cdn.sofifa.net/players/257,578/25_120.png" },
  { id:70,  name:"M. Acuña",       pos:"DEF", ovr:84, club:"Sevilla",        nat:"Argentina",  cardType:"gold",    flag:"🇦🇷", faceUrl:"https://cdn.sofifa.net/players/218,706/25_120.png" },
  { id:71,  name:"D. Alaba",       pos:"DEF", ovr:85, club:"Real Madrid",    nat:"Austria",    cardType:"gold",    flag:"🇦🇹", faceUrl:"https://cdn.sofifa.net/players/186,526/25_120.png" },
  { id:72,  name:"C. Romero",      pos:"DEF", ovr:86, club:"Tottenham",      nat:"Argentina",  cardType:"gold",    flag:"🇦🇷", faceUrl:"https://cdn.sofifa.net/players/246,484/25_120.png" },
  { id:73,  name:"R. White",       pos:"DEF", ovr:85, club:"Arsenal",        nat:"England",    cardType:"gold",    flag:"🏴󠁧󠁢󠁥󠁮󠁧󠁿", faceUrl:"https://cdn.sofifa.net/players/244,561/25_120.png" },
  { id:74,  name:"Rúben Dias",     pos:"DEF", ovr:88, club:"Man City",       nat:"Portugal",   cardType:"gold",    flag:"🇵🇹", faceUrl:"https://cdn.sofifa.net/players/244,728/25_120.png" },
  { id:75,  name:"J. Gvardiol",    pos:"DEF", ovr:86, club:"Man City",       nat:"Croatia",    cardType:"gold",    flag:"🇭🇷", faceUrl:"https://cdn.sofifa.net/players/261,679/25_120.png" },
  { id:76,  name:"Marquinhos",     pos:"DEF", ovr:87, club:"PSG",           nat:"Brazil",     cardType:"gold",    flag:"🇧🇷", faceUrl:"https://cdn.sofifa.net/players/199,306/25_120.png" },
  { id:77,  name:"Militão",        pos:"DEF", ovr:86, club:"Real Madrid",    nat:"Brazil",     cardType:"gold",    flag:"🇧🇷", faceUrl:"https://cdn.sofifa.net/players/247,078/25_120.png" },
  { id:78,  name:"S. Koundé",      pos:"DEF", ovr:85, club:"Barcelona",      nat:"France",     cardType:"gold",    flag:"🇫🇷", faceUrl:"https://cdn.sofifa.net/players/253,332/25_120.png" },

  // ── GOLD MIDs ──────────────────────────────────────
  { id:100, name:"K. De Bruyne",   pos:"MID", ovr:91, club:"Man City",       nat:"Belgium",    cardType:"gold",    flag:"🇧🇪", faceUrl:"https://cdn.sofifa.net/players/192,985/25_120.png" },
  { id:101, name:"T. Kroos",       pos:"MID", ovr:89, club:"Real Madrid",    nat:"Germany",    cardType:"gold",    flag:"🇩🇪", faceUrl:"https://cdn.sofifa.net/players/182,521/25_120.png" },
  { id:102, name:"M. Verratti",    pos:"MID", ovr:87, club:"Al Arabi SC",    nat:"Italy",      cardType:"gold",    flag:"🇮🇹", faceUrl:"https://cdn.sofifa.net/players/193,435/25_120.png" },
  { id:103, name:"L. Goretzka",    pos:"MID", ovr:85, club:"Bayern Munich",  nat:"Germany",    cardType:"gold",    flag:"🇩🇪", faceUrl:"https://cdn.sofifa.net/players/212,560/25_120.png" },
  { id:104, name:"F. Valverde",    pos:"MID", ovr:88, club:"Real Madrid",    nat:"Uruguay",    cardType:"gold",    flag:"🇺🇾", faceUrl:"https://cdn.sofifa.net/players/240,116/25_120.png" },
  { id:105, name:"B. Camavinga",   pos:"MID", ovr:84, club:"Real Madrid",    nat:"France",     cardType:"gold",    flag:"🇫🇷", faceUrl:"https://cdn.sofifa.net/players/267,612/25_120.png" },
  { id:106, name:"P. Foden",       pos:"MID", ovr:88, club:"Man City",       nat:"England",    cardType:"gold",    flag:"🏴󠁧󠁢󠁥󠁮󠁧󠁿", faceUrl:"https://cdn.sofifa.net/players/237,692/25_120.png" },
  { id:107, name:"C. Gallagher",   pos:"MID", ovr:82, club:"Atlético Madrid",nat:"England",    cardType:"gold",    flag:"🏴󠁧󠁢󠁥󠁮󠁧󠁿", faceUrl:"https://cdn.sofifa.net/players/261,177/25_120.png" },
  { id:108, name:"S. Milinkovic-Savic",pos:"MID",ovr:86,club:"Al Hilal",    nat:"Serbia",     cardType:"gold",    flag:"🇷🇸", faceUrl:"https://cdn.sofifa.net/players/207,865/25_120.png" },
  { id:109, name:"E. Fernandez",   pos:"MID", ovr:83, club:"Chelsea",        nat:"Argentina",  cardType:"gold",    flag:"🇦🇷", faceUrl:"https://cdn.sofifa.net/players/264,617/25_120.png" },
  { id:110, name:"D. Rice",        pos:"MID", ovr:86, club:"Arsenal",        nat:"England",    cardType:"gold",    flag:"🏴󠁧󠁢󠁥󠁮󠁧󠁿", faceUrl:"https://cdn.sofifa.net/players/243,269/25_120.png" },
  { id:111, name:"M. Amrabat",     pos:"MID", ovr:81, club:"Fenerbahçe",     nat:"Morocco",    cardType:"gold",    flag:"🇲🇦", faceUrl:"https://cdn.sofifa.net/players/232,548/25_120.png" },
  { id:112, name:"A. Tchouaméni",  pos:"MID", ovr:84, club:"Real Madrid",    nat:"France",     cardType:"gold",    flag:"🇫🇷", faceUrl:"https://cdn.sofifa.net/players/262,049/25_120.png" },
  { id:113, name:"J. Dani Olmo",   pos:"MID", ovr:86, club:"Barcelona",      nat:"Spain",      cardType:"gold",    flag:"🇪🇸", faceUrl:"https://cdn.sofifa.net/players/234,666/25_120.png" },
  { id:114, name:"G. Ramos",       pos:"MID", ovr:84, club:"PSG",           nat:"Portugal",   cardType:"gold",    flag:"🇵🇹", faceUrl:"https://cdn.sofifa.net/players/265,054/25_120.png" },
  { id:115, name:"L. Modric",      pos:"MID", ovr:87, club:"Real Madrid",    nat:"Croatia",    cardType:"gold",    flag:"🇭🇷", faceUrl:"https://cdn.sofifa.net/players/177,003/25_120.png" },
  { id:116, name:"B. Fernandes",   pos:"MID", ovr:86, club:"Man Utd",        nat:"Portugal",   cardType:"gold",    flag:"🇵🇹", faceUrl:"https://cdn.sofifa.net/players/212,198/25_120.png" },
  { id:117, name:"T. Arnold",      pos:"MID", ovr:86, club:"Real Madrid",    nat:"England",    cardType:"gold",    flag:"🏴󠁧󠁢󠁥󠁮󠁧󠁿", faceUrl:"https://cdn.sofifa.net/players/237,790/25_120.png" },
  { id:118, name:"Pedri",          pos:"MID", ovr:87, club:"Barcelona",      nat:"Spain",      cardType:"gold",    flag:"🇪🇸", faceUrl:"https://cdn.sofifa.net/players/272,374/25_120.png" },
  { id:119, name:"G. Donnarumma",  pos:"MID", ovr:83, club:"PSG",           nat:"Italy",      cardType:"gold",    flag:"🇮🇹", faceUrl:"https://cdn.sofifa.net/players/238,194/25_120.png" },

  // ── GOLD ATTs ──────────────────────────────────────
  { id:140, name:"R. Lewandowski", pos:"ATT", ovr:90, club:"Barcelona",      nat:"Poland",     cardType:"gold",    flag:"🇵🇱", faceUrl:"https://cdn.sofifa.net/players/188,545/25_120.png" },
  { id:141, name:"H. Kane",        pos:"ATT", ovr:90, club:"Bayern Munich",  nat:"England",    cardType:"gold",    flag:"🏴󠁧󠁢󠁥󠁮󠁧󠁿", faceUrl:"https://cdn.sofifa.net/players/202,126/25_120.png" },
  { id:142, name:"O. Giroud",      pos:"ATT", ovr:82, club:"LA Galaxy",      nat:"France",     cardType:"gold",    flag:"🇫🇷", faceUrl:"https://cdn.sofifa.net/players/182,521/25_120.png" },
  { id:143, name:"A. Griezmann",   pos:"ATT", ovr:87, club:"Atlético Madrid",nat:"France",     cardType:"gold",    flag:"🇫🇷", faceUrl:"https://cdn.sofifa.net/players/194,765/25_120.png" },
  { id:144, name:"L. Suárez",      pos:"ATT", ovr:85, club:"Inter Miami",    nat:"Uruguay",    cardType:"gold",    flag:"🇺🇾", faceUrl:"https://cdn.sofifa.net/players/176,580/25_120.png" },
  { id:145, name:"N. Zirkzee",     pos:"ATT", ovr:82, club:"Man Utd",        nat:"Netherlands",cardType:"gold",    flag:"🇳🇱", faceUrl:"https://cdn.sofifa.net/players/263,752/25_120.png" },
  { id:146, name:"M. Guendouzi",   pos:"ATT", ovr:81, club:"Marseille",      nat:"France",     cardType:"gold",    flag:"🇫🇷", faceUrl:"https://cdn.sofifa.net/players/246,497/25_120.png" },
  { id:147, name:"S. Gnabry",      pos:"ATT", ovr:84, club:"Bayern Munich",  nat:"Germany",    cardType:"gold",    flag:"🇩🇪", faceUrl:"https://cdn.sofifa.net/players/213,345/25_120.png" },
  { id:148, name:"C. Pulisic",     pos:"ATT", ovr:82, club:"AC Milan",       nat:"USA",        cardType:"gold",    flag:"🇺🇸", faceUrl:"https://cdn.sofifa.net/players/224,685/25_120.png" },
  { id:149, name:"M. Rashford",    pos:"ATT", ovr:83, club:"Aston Villa",    nat:"England",    cardType:"gold",    flag:"🏴󠁧󠁢󠁥󠁮󠁧󠁿", faceUrl:"https://cdn.sofifa.net/players/233,967/25_120.png" },
  { id:150, name:"K. Havertz",     pos:"ATT", ovr:84, club:"Arsenal",        nat:"Germany",    cardType:"gold",    flag:"🇩🇪", faceUrl:"https://cdn.sofifa.net/players/238,794/25_120.png" },
  { id:151, name:"D. Nunez",       pos:"ATT", ovr:84, club:"Liverpool",      nat:"Uruguay",    cardType:"gold",    flag:"🇺🇾", faceUrl:"https://cdn.sofifa.net/players/262,174/25_120.png" },
  { id:152, name:"G. Jesus",       pos:"ATT", ovr:82, club:"Arsenal",        nat:"Brazil",     cardType:"gold",    flag:"🇧🇷", faceUrl:"https://cdn.sofifa.net/players/221,814/25_120.png" },
  { id:153, name:"W. Zaha",        pos:"ATT", ovr:81, club:"Galatasaray",    nat:"Ivory Coast",cardType:"gold",    flag:"🇨🇮", faceUrl:"https://cdn.sofifa.net/players/192,476/25_120.png" },
  { id:154, name:"M. Lacazette",   pos:"ATT", ovr:82, club:"Lyon",           nat:"France",     cardType:"gold",    flag:"🇫🇷", faceUrl:"https://cdn.sofifa.net/players/189,332/25_120.png" },
  { id:155, name:"C. Torres",      pos:"ATT", ovr:82, club:"Barcelona",      nat:"Spain",      cardType:"gold",    flag:"🇪🇸", faceUrl:"https://cdn.sofifa.net/players/259,867/25_120.png" },
  { id:156, name:"G. Bale",        pos:"ATT", ovr:85, club:"LAFC (Icon)",    nat:"Wales",      cardType:"gold",    flag:"🏴󠁧󠁢󠁷󠁬󠁳󠁿", faceUrl:"https://cdn.sofifa.net/players/183,898/25_120.png" },
  { id:157, name:"A. Saka",        pos:"ATT", ovr:87, club:"Arsenal",        nat:"England",    cardType:"gold",    flag:"🏴󠁧󠁢󠁥󠁮󠁧󠁿", faceUrl:"https://cdn.sofifa.net/players/259,685/25_120.png" },
  { id:158, name:"L. Diaz",        pos:"ATT", ovr:84, club:"Liverpool",      nat:"Colombia",   cardType:"gold",    flag:"🇨🇴", faceUrl:"https://cdn.sofifa.net/players/243,069/25_120.png" },
  { id:159, name:"M. Depay",       pos:"ATT", ovr:82, club:"Atlético Madrid",nat:"Netherlands",cardType:"gold",    flag:"🇳🇱", faceUrl:"https://cdn.sofifa.net/players/202,609/25_120.png" },
  { id:160, name:"O. Dembélé",     pos:"ATT", ovr:86, club:"PSG",           nat:"France",     cardType:"gold",    flag:"🇫🇷", faceUrl:"https://cdn.sofifa.net/players/214,779/25_120.png" },
  { id:161, name:"B. Diallo",      pos:"ATT", ovr:81, club:"Arsenal",        nat:"Guinea",     cardType:"gold",    flag:"🇬🇳", faceUrl:"https://cdn.sofifa.net/players/267,912/25_120.png" },
  { id:162, name:"R. Osimhen",     pos:"ATT", ovr:88, club:"Galatasaray",    nat:"Nigeria",    cardType:"gold",    flag:"🇳🇬", faceUrl:"https://cdn.sofifa.net/players/246,458/25_120.png" },
  { id:163, name:"K. Lukaku",      pos:"ATT", ovr:85, club:"Napoli",         nat:"Belgium",    cardType:"gold",    flag:"🇧🇪", faceUrl:"https://cdn.sofifa.net/players/192,476/25_120.png" },

  // ── MORE GKs (silver) ─────────────────────────────
  { id:170, name:"B. Leno",        pos:"GK",  ovr:83, club:"Fulham",         nat:"Germany",    cardType:"silver",  flag:"🇩🇪", faceUrl:"https://cdn.sofifa.net/players/196,493/25_120.png" },
  { id:171, name:"W. Henderson",   pos:"GK",  ovr:82, club:"Ajax",           nat:"England",    cardType:"silver",  flag:"🏴󠁧󠁢󠁥󠁮󠁧󠁿", faceUrl:"https://cdn.sofifa.net/players/213,993/25_120.png" },
  { id:172, name:"V. Forsberg",    pos:"GK",  ovr:81, club:"Leipzig",        nat:"Sweden",     cardType:"silver",  flag:"🇸🇪", faceUrl:"https://cdn.sofifa.net/players/223,432/25_120.png" },
  { id:173, name:"N. Pope",        pos:"GK",  ovr:82, club:"Newcastle",      nat:"England",    cardType:"silver",  flag:"🏴󠁧󠁢󠁥󠁮󠁧󠁿", faceUrl:"https://cdn.sofifa.net/players/211,240/25_120.png" },
  { id:174, name:"D. Henderson",   pos:"GK",  ovr:81, club:"Crystal Palace", nat:"England",    cardType:"silver",  flag:"🏴󠁧󠁢󠁥󠁮󠁧󠁿", faceUrl:"https://cdn.sofifa.net/players/234,414/25_120.png" },

  // ── MORE DEFs (silver) ────────────────────────────
  { id:180, name:"K. Walker",      pos:"DEF", ovr:83, club:"Man City",       nat:"England",    cardType:"silver",  flag:"🏴󠁧󠁢󠁥󠁮󠁧󠁿", faceUrl:"https://cdn.sofifa.net/players/174,590/25_120.png" },
  { id:181, name:"B. Chilwell",    pos:"DEF", ovr:82, club:"Chelsea",        nat:"England",    cardType:"silver",  flag:"🏴󠁧󠁢󠁥󠁮󠁧󠁿", faceUrl:"https://cdn.sofifa.net/players/236,697/25_120.png" },
  { id:182, name:"T. Azpilicueta", pos:"DEF", ovr:81, club:"Español",        nat:"Spain",      cardType:"silver",  flag:"🇪🇸", faceUrl:"https://cdn.sofifa.net/players/178,603/25_120.png" },
  { id:183, name:"M. Dunk",        pos:"DEF", ovr:80, club:"Brighton",       nat:"England",    cardType:"silver",  flag:"🏴󠁧󠁢󠁥󠁮󠁧󠁿", faceUrl:"https://cdn.sofifa.net/players/189,341/25_120.png" },
  { id:184, name:"J. Timber",      pos:"DEF", ovr:83, club:"Arsenal",        nat:"Netherlands",cardType:"silver",  flag:"🇳🇱", faceUrl:"https://cdn.sofifa.net/players/264,634/25_120.png" },
  { id:185, name:"T. Alexander-Arnold",pos:"DEF",ovr:86,club:"Real Madrid",  nat:"England",    cardType:"silver",  flag:"🏴󠁧󠁢󠁥󠁮󠁧󠁿", faceUrl:"https://cdn.sofifa.net/players/237,790/25_120.png" },
  { id:186, name:"A. Davies",      pos:"DEF", ovr:84, club:"Bayern Munich",  nat:"Canada",     cardType:"silver",  flag:"🇨🇦", faceUrl:"https://cdn.sofifa.net/players/239,084/25_120.png" },
  { id:187, name:"N. Otamendi",    pos:"DEF", ovr:82, club:"Benfica",        nat:"Argentina",  cardType:"silver",  flag:"🇦🇷", faceUrl:"https://cdn.sofifa.net/players/184,344/25_120.png" },
  { id:188, name:"C. Bisseck",     pos:"DEF", ovr:80, club:"Inter Milan",    nat:"Germany",    cardType:"silver",  flag:"🇩🇪", faceUrl:"https://cdn.sofifa.net/players/260,456/25_120.png" },
  { id:189, name:"L. Morales",     pos:"DEF", ovr:79, club:"Villarreal",     nat:"Spain",      cardType:"silver",  flag:"🇪🇸", faceUrl:"https://cdn.sofifa.net/players/234,651/25_120.png" },

  // ── MORE MIDs (silver/gold) ───────────────────────
  { id:200, name:"N. Kante",       pos:"MID", ovr:85, club:"Al-Ittihad",     nat:"France",     cardType:"gold",    flag:"🇫🇷", faceUrl:"https://cdn.sofifa.net/players/215,914/25_120.png" },
  { id:201, name:"R. Brozovic",    pos:"MID", ovr:83, club:"Al Nassr",       nat:"Croatia",    cardType:"silver",  flag:"🇭🇷", faceUrl:"https://cdn.sofifa.net/players/193,040/25_120.png" },
  { id:202, name:"T. Partey",      pos:"MID", ovr:83, club:"Arsenal",        nat:"Ghana",      cardType:"silver",  flag:"🇬🇭", faceUrl:"https://cdn.sofifa.net/players/212,681/25_120.png" },
  { id:203, name:"M. Kovacic",     pos:"MID", ovr:84, club:"Man City",       nat:"Croatia",    cardType:"silver",  flag:"🇭🇷", faceUrl:"https://cdn.sofifa.net/players/196,477/25_120.png" },
  { id:204, name:"J. Maddison",    pos:"MID", ovr:83, club:"Newcastle",      nat:"England",    cardType:"silver",  flag:"🏴󠁧󠁢󠁥󠁮󠁧󠁿", faceUrl:"https://cdn.sofifa.net/players/218,094/25_120.png" },
  { id:205, name:"A. Ruiz",        pos:"MID", ovr:81, club:"Napoli",         nat:"Spain",      cardType:"silver",  flag:"🇪🇸", faceUrl:"https://cdn.sofifa.net/players/242,299/25_120.png" },
  { id:206, name:"S. Sakai",       pos:"MID", ovr:78, club:"Urawa Reds",     nat:"Japan",      cardType:"silver",  flag:"🇯🇵", faceUrl:"https://cdn.sofifa.net/players/202,031/25_120.png" },
  { id:207, name:"Y. Bissouma",    pos:"MID", ovr:82, club:"Tottenham",      nat:"Mali",       cardType:"silver",  flag:"🇲🇱", faceUrl:"https://cdn.sofifa.net/players/234,548/25_120.png" },
  { id:208, name:"A. Guendouzi",   pos:"MID", ovr:82, club:"Marseille",      nat:"France",     cardType:"silver",  flag:"🇫🇷", faceUrl:"https://cdn.sofifa.net/players/246,497/25_120.png" },
  { id:209, name:"C. Nkunku",      pos:"MID", ovr:85, club:"Chelsea",        nat:"France",     cardType:"gold",    flag:"🇫🇷", faceUrl:"https://cdn.sofifa.net/players/242,903/25_120.png" },
  { id:210, name:"M. Frattesi",    pos:"MID", ovr:82, club:"Inter Milan",    nat:"Italy",      cardType:"silver",  flag:"🇮🇹", faceUrl:"https://cdn.sofifa.net/players/246,452/25_120.png" },
  { id:211, name:"A. Miranchuk",   pos:"MID", ovr:80, club:"Atalanta",       nat:"Russia",     cardType:"silver",  flag:"🇷🇺", faceUrl:"https://cdn.sofifa.net/players/226,452/25_120.png" },
  { id:212, name:"M. Mount",       pos:"MID", ovr:82, club:"Man Utd",        nat:"England",    cardType:"silver",  flag:"🏴󠁧󠁢󠁥󠁮󠁧󠁿", faceUrl:"https://cdn.sofifa.net/players/241,641/25_120.png" },

  // ── MORE ATTs (silver/gold) ───────────────────────
  { id:220, name:"O. Watkins",     pos:"ATT", ovr:84, club:"Aston Villa",    nat:"England",    cardType:"gold",    flag:"🏴󠁧󠁢󠁥󠁮󠁧󠁿", faceUrl:"https://cdn.sofifa.net/players/234,519/25_120.png" },
  { id:221, name:"A. Martial",     pos:"ATT", ovr:80, club:"Sevilla",        nat:"France",     cardType:"silver",  flag:"🇫🇷", faceUrl:"https://cdn.sofifa.net/players/207,646/25_120.png" },
  { id:222, name:"D. Zapata",      pos:"ATT", ovr:81, club:"Torino",         nat:"Colombia",   cardType:"silver",  flag:"🇨🇴", faceUrl:"https://cdn.sofifa.net/players/199,570/25_120.png" },
  { id:223, name:"A. Abraham",     pos:"ATT", ovr:82, club:"AS Roma",        nat:"England",    cardType:"silver",  flag:"🏴󠁧󠁢󠁥󠁮󠁧󠁿", faceUrl:"https://cdn.sofifa.net/players/238,823/25_120.png" },
  { id:224, name:"T. Awoniyi",     pos:"ATT", ovr:80, club:"Nottm Forest",   nat:"Nigeria",    cardType:"silver",  flag:"🇳🇬", faceUrl:"https://cdn.sofifa.net/players/228,348/25_120.png" },
  { id:225, name:"B. Brereton",    pos:"ATT", ovr:77, club:"Villarreal",     nat:"Chile",      cardType:"silver",  flag:"🇨🇱", faceUrl:"https://cdn.sofifa.net/players/243,251/25_120.png" },
  { id:226, name:"P. Aubameyang",  pos:"ATT", ovr:82, club:"Marseille",      nat:"Gabon",      cardType:"silver",  flag:"🇬🇦", faceUrl:"https://cdn.sofifa.net/players/176,928/25_120.png" },
  { id:227, name:"C. Adams",       pos:"ATT", ovr:79, club:"Southampton",    nat:"Scotland",   cardType:"silver",  flag:"🏴󠁧󠁢󠁳󠁣󠁴󠁿", faceUrl:"https://cdn.sofifa.net/players/238,521/25_120.png" },
  { id:228, name:"M. Dias",        pos:"ATT", ovr:80, club:"Wolves",         nat:"Portugal",   cardType:"silver",  flag:"🇵🇹", faceUrl:"https://cdn.sofifa.net/players/261,592/25_120.png" },
  { id:229, name:"B. Furlong",     pos:"ATT", ovr:77, club:"Barnsley",       nat:"Ireland",    cardType:"silver",  flag:"🇮🇪", faceUrl:"https://cdn.sofifa.net/players/244,512/25_120.png" },
  { id:230, name:"R. Firmino",     pos:"ATT", ovr:82, club:"Al-Ahli",        nat:"Brazil",     cardType:"silver",  flag:"🇧🇷", faceUrl:"https://cdn.sofifa.net/players/200,643/25_120.png" },
  { id:231, name:"M. Milik",       pos:"ATT", ovr:81, club:"Juventus",       nat:"Poland",     cardType:"silver",  flag:"🇵🇱", faceUrl:"https://cdn.sofifa.net/players/198,385/25_120.png" },
  { id:232, name:"B. Ekitike",     pos:"ATT", ovr:80, club:"Frankfurt",      nat:"France",     cardType:"silver",  flag:"🇫🇷", faceUrl:"https://cdn.sofifa.net/players/268,450/25_120.png" },
  { id:233, name:"I. Sarr",        pos:"ATT", ovr:81, club:"Crystal Palace", nat:"Senegal",    cardType:"silver",  flag:"🇸🇳", faceUrl:"https://cdn.sofifa.net/players/243,242/25_120.png" },
  { id:234, name:"A. Solanke",     pos:"ATT", ovr:81, club:"Man Utd",        nat:"England",    cardType:"silver",  flag:"🏴󠁧󠁢󠁥󠁮󠁧󠁿", faceUrl:"https://cdn.sofifa.net/players/220,785/25_120.png" },

  // ── Additional Legends to round out 200+ ─────────
  { id:240, name:"Rivaldo",        pos:"ATT", ovr:95, club:"Barcelona (I)",  nat:"Brazil",     cardType:"legend",  flag:"🇧🇷", faceUrl:"https://cdn.sofifa.net/players/152,013/25_120.png" },
  { id:241, name:"Bergkamp",       pos:"ATT", ovr:92, club:"Arsenal (Icon)", nat:"Netherlands",cardType:"legend",  flag:"🇳🇱", faceUrl:"https://cdn.sofifa.net/players/152,046/25_120.png" },
  { id:242, name:"Vieira",         pos:"MID", ovr:91, club:"Arsenal (Icon)", nat:"France",     cardType:"legend",  flag:"🇫🇷", faceUrl:"https://cdn.sofifa.net/players/152,058/25_120.png" },
  { id:243, name:"Scholes",        pos:"MID", ovr:91, club:"Man Utd (Icon)", nat:"England",    cardType:"legend",  flag:"🏴󠁧󠁢󠁥󠁮󠁧󠁿", faceUrl:"https://cdn.sofifa.net/players/152,052/25_120.png" },
  { id:244, name:"Giggs",          pos:"ATT", ovr:90, club:"Man Utd (Icon)", nat:"Wales",      cardType:"legend",  flag:"🏴󠁧󠁢󠁷󠁬󠁳󠁿", faceUrl:"https://cdn.sofifa.net/players/152,036/25_120.png" },
  { id:245, name:"Deco",           pos:"MID", ovr:89, club:"Barcelona (I)",  nat:"Portugal",   cardType:"legend",  flag:"🇵🇹", faceUrl:"https://cdn.sofifa.net/players/162,641/25_120.png" },
  { id:246, name:"Davids",         pos:"MID", ovr:88, club:"Juventus (I)",   nat:"Netherlands",cardType:"legend",  flag:"🇳🇱", faceUrl:"https://cdn.sofifa.net/players/152,065/25_120.png" },
  { id:247, name:"Raúl",           pos:"ATT", ovr:91, club:"Real Madrid (I)",nat:"Spain",      cardType:"legend",  flag:"🇪🇸", faceUrl:"https://cdn.sofifa.net/players/152,010/25_120.png" },
  { id:248, name:"R. Baggio",      pos:"ATT", ovr:93, club:"Juventus (I)",   nat:"Italy",      cardType:"legend",  flag:"🇮🇹", faceUrl:"https://cdn.sofifa.net/players/152,018/25_120.png" },
  { id:249, name:"Eusébio",        pos:"ATT", ovr:95, club:"Benfica (Icon)", nat:"Portugal",   cardType:"legend",  flag:"🇵🇹", faceUrl:"https://cdn.sofifa.net/players/102,829/25_120.png" },
  { id:250, name:"G. Best",        pos:"ATT", ovr:94, club:"Man Utd (Icon)", nat:"N. Ireland", cardType:"legend",  flag:"🇬🇧", faceUrl:"https://cdn.sofifa.net/players/102,832/25_120.png" },
  { id:251, name:"J. Charlton",    pos:"DEF", ovr:90, club:"Man Utd (Icon)", nat:"England",    cardType:"legend",  flag:"🏴󠁧󠁢󠁥󠁮󠁧󠁿", faceUrl:"https://cdn.sofifa.net/players/102,841/25_120.png" },
  { id:252, name:"M. Platini",     pos:"MID", ovr:95, club:"Juventus (I)",   nat:"France",     cardType:"legend",  flag:"🇫🇷", faceUrl:"https://cdn.sofifa.net/players/102,836/25_120.png" },
  { id:253, name:"K. Dalglish",    pos:"ATT", ovr:91, club:"Liverpool (I)",  nat:"Scotland",   cardType:"legend",  flag:"🏴󠁧󠁢󠁳󠁣󠁴󠁿", faceUrl:"https://cdn.sofifa.net/players/102,845/25_120.png" },
  { id:254, name:"Gerd Müller",    pos:"ATT", ovr:95, club:"Bayern (Icon)",  nat:"Germany",    cardType:"legend",  flag:"🇩🇪", faceUrl:"https://cdn.sofifa.net/players/102,843/25_120.png" },
  { id:255, name:"F. Baresi",      pos:"DEF", ovr:93, club:"AC Milan (I)",   nat:"Italy",      cardType:"legend",  flag:"🇮🇹", faceUrl:"https://cdn.sofifa.net/players/102,847/25_120.png" },
  { id:256, name:"Gullit",         pos:"ATT", ovr:94, club:"AC Milan (I)",   nat:"Netherlands",cardType:"legend",  flag:"🇳🇱", faceUrl:"https://cdn.sofifa.net/players/102,834/25_120.png" },
  { id:257, name:"A. del Piero",   pos:"ATT", ovr:93, club:"Juventus (I)",   nat:"Italy",      cardType:"legend",  flag:"🇮🇹", faceUrl:"https://cdn.sofifa.net/players/152,004/25_120.png" },
  { id:258, name:"O. Bierhoff",    pos:"ATT", ovr:87, club:"Udinese (I)",    nat:"Germany",    cardType:"legend",  flag:"🇩🇪", faceUrl:"https://cdn.sofifa.net/players/152,087/25_120.png" },
  { id:259, name:"Klinsmann",      pos:"ATT", ovr:89, club:"B. Munich (I)",  nat:"Germany",    cardType:"legend",  flag:"🇩🇪", faceUrl:"https://cdn.sofifa.net/players/102,851/25_120.png" },
  { id:260, name:"B. Laudrup",     pos:"MID", ovr:91, club:"Barcelona (I)",  nat:"Denmark",    cardType:"legend",  flag:"🇩🇰", faceUrl:"https://cdn.sofifa.net/players/102,853/25_120.png" },
  { id:261, name:"J. Litmanen",    pos:"MID", ovr:89, club:"Ajax (Icon)",    nat:"Finland",    cardType:"legend",  flag:"🇫🇮", faceUrl:"https://cdn.sofifa.net/players/152,078/25_120.png" },
  { id:262, name:"R. Gullit",      pos:"MID", ovr:93, club:"AC Milan (I)",   nat:"Netherlands",cardType:"legend",  flag:"🇳🇱", faceUrl:"https://cdn.sofifa.net/players/152,021/25_120.png" },
  { id:263, name:"P. Maldini",     pos:"DEF", ovr:95, club:"AC Milan (I)",   nat:"Italy",      cardType:"legend",  flag:"🇮🇹", faceUrl:"https://cdn.sofifa.net/players/152,001/25_120.png" },
  { id:264, name:"G. Hagi",        pos:"MID", ovr:90, club:"Real Madrid (I)",nat:"Romania",    cardType:"legend",  flag:"🇷🇴", faceUrl:"https://cdn.sofifa.net/players/102,861/25_120.png" },
  { id:265, name:"Stoichkov",      pos:"ATT", ovr:91, club:"Barcelona (I)",  nat:"Bulgaria",   cardType:"legend",  flag:"🇧🇬", faceUrl:"https://cdn.sofifa.net/players/102,863/25_120.png" },
  { id:266, name:"Lato",           pos:"DEF", ovr:87, club:"Valencia (I)",   nat:"Spain",      cardType:"legend",  flag:"🇪🇸", faceUrl:"https://cdn.sofifa.net/players/102,875/25_120.png" },

  // ── Rising Stars ─────────────────────────────────
  { id:280, name:"G. Ramos",       pos:"ATT", ovr:82, club:"PSG",           nat:"Portugal",   cardType:"gold",    flag:"🇵🇹", faceUrl:"https://cdn.sofifa.net/players/265,054/25_120.png" },
  { id:281, name:"J. Gavi",        pos:"MID", ovr:85, club:"Barcelona",      nat:"Spain",      cardType:"gold",    flag:"🇪🇸", faceUrl:"https://cdn.sofifa.net/players/272,547/25_120.png" },
  { id:282, name:"E. Camavinga",   pos:"MID", ovr:83, club:"Real Madrid",    nat:"France",     cardType:"gold",    flag:"🇫🇷", faceUrl:"https://cdn.sofifa.net/players/267,612/25_120.png" },
  { id:283, name:"F. Bayo",        pos:"ATT", ovr:78, club:"Strasbourg",     nat:"Guinea",     cardType:"silver",  flag:"🇬🇳", faceUrl:"https://cdn.sofifa.net/players/269,350/25_120.png" },
  { id:284, name:"M. Diatta",      pos:"ATT", ovr:78, club:"Monaco",         nat:"Senegal",    cardType:"silver",  flag:"🇸🇳", faceUrl:"https://cdn.sofifa.net/players/243,230/25_120.png" },
  { id:285, name:"J. Bellingham",  pos:"ATT", ovr:85, club:"Real Madrid",    nat:"England",    cardType:"gold",    flag:"🏴󠁧󠁢󠁥󠁮󠁧󠁿", faceUrl:"https://cdn.sofifa.net/players/256,560/25_120.png" },
  { id:286, name:"C. Hudson-Odoi", pos:"ATT", ovr:79, club:"Nottm Forest",   nat:"England",    cardType:"silver",  flag:"🏴󠁧󠁢󠁥󠁮󠁧󠁿", faceUrl:"https://cdn.sofifa.net/players/241,453/25_120.png" },
  { id:287, name:"G. Martinelli",  pos:"ATT", ovr:83, club:"Arsenal",        nat:"Brazil",     cardType:"gold",    flag:"🇧🇷", faceUrl:"https://cdn.sofifa.net/players/264,773/25_120.png" },
  { id:288, name:"A. Gnonto",      pos:"ATT", ovr:77, club:"Leeds Utd",      nat:"Italy",      cardType:"silver",  flag:"🇮🇹", faceUrl:"https://cdn.sofifa.net/players/271,350/25_120.png" },
  { id:289, name:"O. Lukeba",      pos:"DEF", ovr:80, club:"Leipzig",        nat:"France",     cardType:"silver",  flag:"🇫🇷", faceUrl:"https://cdn.sofifa.net/players/272,456/25_120.png" },
  { id:290, name:"C. Nkosi",       pos:"DEF", ovr:76, club:"Marseille",      nat:"France",     cardType:"silver",  flag:"🇫🇷", faceUrl:"https://cdn.sofifa.net/players/273,210/25_120.png" },
  { id:291, name:"Y. Tielemans",   pos:"MID", ovr:83, club:"Aston Villa",    nat:"Belgium",    cardType:"silver",  flag:"🇧🇪", faceUrl:"https://cdn.sofifa.net/players/214,047/25_120.png" },
  { id:292, name:"I. Iliev",       pos:"GK",  ovr:76, club:"Chelsea",        nat:"Bulgaria",   cardType:"silver",  flag:"🇧🇬", faceUrl:"https://cdn.sofifa.net/players/271,380/25_120.png" },
  { id:293, name:"M. Gavin",       pos:"DEF", ovr:74, club:"Wigan",          nat:"Australia",  cardType:"silver",  flag:"🇦🇺", faceUrl:"https://cdn.sofifa.net/players/274,510/25_120.png" },
  { id:294, name:"K. Guehi",       pos:"DEF", ovr:82, club:"Crystal Palace", nat:"England",    cardType:"silver",  flag:"🏴󠁧󠁢󠁥󠁮󠁧󠁿", faceUrl:"https://cdn.sofifa.net/players/255,847/25_120.png" },
];

// Position categories
export const POS_MAP = {
  GK:  'GK',
  DEF: 'DEF',
  MID: 'MID',
  ATT: 'ATT',
};

// Return a shuffled copy of the player pool
export function buildPlayerPool() {
  return [...PLAYERS].sort(() => Math.random() - 0.5);
}
