// ═══════════════════════════════════════════════════════
//  database.js — 350+ Verified FUT Stars & Legends Database
//  Accurate positions, real Sofifa player face photo URLs
// ═══════════════════════════════════════════════════════

export const PLAYERS = [
  // ── LEGENDS (Icons) ──────────────────────────────────
  { id:1,   name:"L. Messi",       pos:"ATT", subPos:"RW",  ovr:93, club:"Inter Miami",    nat:"Argentina",  cardType:"legend",  flag:"🇦🇷", faceUrl:"https://cdn.sofifa.net/players/158/023/25_120.png" },
  { id:2,   name:"C. Ronaldo",     pos:"ATT", subPos:"ST",  ovr:91, club:"Al Nassr",       nat:"Portugal",   cardType:"legend",  flag:"🇵🇹", faceUrl:"https://cdn.sofifa.net/players/020/801/25_120.png" },
  { id:3,   name:"Pelé",           pos:"ATT", subPos:"ST",  ovr:98, club:"Santos (Icon)",  nat:"Brazil",     cardType:"legend",  flag:"🇧🇷", faceUrl:"https://cdn.sofifa.net/players/102/823/25_120.png" },
  { id:4,   name:"Maradona",       pos:"ATT", subPos:"CAM", ovr:97, club:"Napoli (Icon)",  nat:"Argentina",  cardType:"legend",  flag:"🇦🇷", faceUrl:"https://cdn.sofifa.net/players/102/872/25_120.png" },
  { id:5,   name:"Ronaldinho",     pos:"ATT", subPos:"LW",  ovr:96, club:"Barcelona (I)",  nat:"Brazil",     cardType:"legend",  flag:"🇧🇷", faceUrl:"https://cdn.sofifa.net/players/131/976/25_120.png" },
  { id:6,   name:"Zidane",         pos:"MID", subPos:"CAM", ovr:96, club:"Real Madrid (I)",nat:"France",     cardType:"legend",  flag:"🇫🇷", faceUrl:"https://cdn.sofifa.net/players/101/669/25_120.png" },
  { id:7,   name:"Cruyff",         pos:"ATT", subPos:"ST",  ovr:97, club:"Ajax (Icon)",    nat:"Netherlands",cardType:"legend",  flag:"🇳🇱", faceUrl:"https://cdn.sofifa.net/players/102/824/25_120.png" },
  { id:8,   name:"Ronaldo R9",     pos:"ATT", subPos:"ST",  ovr:97, club:"Real Madrid (I)",nat:"Brazil",     cardType:"legend",  flag:"🇧🇷", faceUrl:"https://cdn.sofifa.net/players/102/820/25_120.png" },
  { id:9,   name:"Maldini",        pos:"DEF", subPos:"CB",  ovr:96, club:"AC Milan (Icon)",nat:"Italy",      cardType:"legend",  flag:"🇮🇹", faceUrl:"https://cdn.sofifa.net/players/102/879/25_120.png" },
  { id:10,  name:"Buffon",         pos:"GK",  subPos:"GK",  ovr:91, club:"Juventus (Icon)",nat:"Italy",      cardType:"legend",  flag:"🇮🇹", faceUrl:"https://cdn.sofifa.net/players/152/040/25_120.png" },
  { id:11,  name:"Yashin",         pos:"GK",  subPos:"GK",  ovr:95, club:"Dynamo (Icon)", nat:"USSR",        cardType:"legend",  flag:"🇷🇺", faceUrl:"https://cdn.sofifa.net/players/102/825/25_120.png" },
  { id:12,  name:"Beckham",        pos:"MID", subPos:"RM",  ovr:92, club:"Man Utd (Icon)", nat:"England",    cardType:"legend",  flag:"🏴󠁧󠁢󠁥󠁮󠁧󠁿", faceUrl:"https://cdn.sofifa.net/players/152/048/25_120.png" },
  { id:13,  name:"Henry",          pos:"ATT", subPos:"LW",  ovr:95, club:"Arsenal (Icon)", nat:"France",     cardType:"legend",  flag:"🇫🇷", faceUrl:"https://cdn.sofifa.net/players/145/715/25_120.png" },
  { id:14,  name:"Shevchenko",     pos:"ATT", subPos:"ST",  ovr:91, club:"AC Milan (Icon)",nat:"Ukraine",    cardType:"legend",  flag:"🇺🇦", faceUrl:"https://cdn.sofifa.net/players/152/050/25_120.png" },
  { id:15,  name:"Gerrard",        pos:"MID", subPos:"CM",  ovr:91, club:"Liverpool (I)",  nat:"England",    cardType:"legend",  flag:"🏴󠁧󠁢󠁥󠁮󠁧󠁿", faceUrl:"https://cdn.sofifa.net/players/152/476/25_120.png" },
  { id:16,  name:"Lampard",        pos:"MID", subPos:"CM",  ovr:91, club:"Chelsea (Icon)", nat:"England",    cardType:"legend",  flag:"🏴󠁧󠁢󠁥󠁮󠁧󠁿", faceUrl:"https://cdn.sofifa.net/players/152/511/25_120.png" },
  { id:17,  name:"Pirlo",          pos:"MID", subPos:"CDM", ovr:92, club:"Juventus (I)",   nat:"Italy",      cardType:"legend",  flag:"🇮🇹", faceUrl:"https://cdn.sofifa.net/players/162/649/25_120.png" },
  { id:18,  name:"Xavi",           pos:"MID", subPos:"CM",  ovr:92, club:"Barcelona (I)",  nat:"Spain",      cardType:"legend",  flag:"🇪🇸", faceUrl:"https://cdn.sofifa.net/players/152/547/25_120.png" },
  { id:19,  name:"Iniesta",        pos:"MID", subPos:"CM",  ovr:91, club:"Barcelona (I)",  nat:"Spain",      cardType:"legend",  flag:"🇪🇸", faceUrl:"https://cdn.sofifa.net/players/159/212/25_120.png" },
  { id:20,  name:"Cafu",           pos:"DEF", subPos:"RB",  ovr:90, club:"AC Milan (Icon)",nat:"Brazil",     cardType:"legend",  flag:"🇧🇷", faceUrl:"https://cdn.sofifa.net/players/102/818/25_120.png" },
  { id:21,  name:"R. Carlos",      pos:"DEF", subPos:"LB",  ovr:92, club:"Real Madrid (I)",nat:"Brazil",     cardType:"legend",  flag:"🇧🇷", faceUrl:"https://cdn.sofifa.net/players/102/819/25_120.png" },
  { id:22,  name:"Cantona",        pos:"ATT", subPos:"ST",  ovr:91, club:"Man Utd (Icon)", nat:"France",     cardType:"legend",  flag:"🇫🇷", faceUrl:"https://cdn.sofifa.net/players/102/826/25_120.png" },
  { id:23,  name:"Nedvěd",         pos:"MID", subPos:"LM",  ovr:90, club:"Juventus (I)",   nat:"Czech Rep.", cardType:"legend",  flag:"🇨🇿", faceUrl:"https://cdn.sofifa.net/players/152/044/25_120.png" },
  { id:24,  name:"Totti",          pos:"ATT", subPos:"CAM", ovr:91, club:"Roma (Icon)",    nat:"Italy",      cardType:"legend",  flag:"🇮🇹", faceUrl:"https://cdn.sofifa.net/players/152/012/25_120.png" },
  { id:25,  name:"Van Basten",     pos:"ATT", subPos:"ST",  ovr:96, club:"AC Milan (Icon)",nat:"Netherlands",cardType:"legend",  flag:"🇳🇱", faceUrl:"https://cdn.sofifa.net/players/102/833/25_120.png" },

  // ── SPECIAL / TOTY ACTIVE STARS ─────────────────────
  { id:26,  name:"K. Mbappé",      pos:"ATT", subPos:"ST",  ovr:91, club:"Real Madrid",    nat:"France",     cardType:"special", flag:"🇫🇷", faceUrl:"https://cdn.sofifa.net/players/231/747/25_120.png" },
  { id:27,  name:"E. Haaland",     pos:"ATT", subPos:"ST",  ovr:91, club:"Man City",       nat:"Norway",     cardType:"special", flag:"🇳🇴", faceUrl:"https://cdn.sofifa.net/players/239/085/25_120.png" },
  { id:28,  name:"Vinícius Jr.",   pos:"ATT", subPos:"LW",  ovr:90, club:"Real Madrid",    nat:"Brazil",     cardType:"special", flag:"🇧🇷", faceUrl:"https://cdn.sofifa.net/players/254/530/25_120.png" },
  { id:29,  name:"J. Bellingham",  pos:"MID", subPos:"CAM", ovr:90, club:"Real Madrid",    nat:"England",    cardType:"special", flag:"🏴󠁧󠁢󠁥󠁮󠁧󠁿", faceUrl:"https://cdn.sofifa.net/players/256/560/25_120.png" },
  { id:30,  name:"Lamine Yamal",   pos:"ATT", subPos:"RW",  ovr:84, club:"Barcelona",      nat:"Spain",      cardType:"special", flag:"🇪🇸", faceUrl:"https://cdn.sofifa.net/players/278/603/25_120.png" },
  { id:31,  name:"Rodri",          pos:"MID", subPos:"CDM", ovr:91, club:"Man City",       nat:"Spain",      cardType:"special", flag:"🇪🇸", faceUrl:"https://cdn.sofifa.net/players/231/869/25_120.png" },
  { id:32,  name:"R. Leão",        pos:"ATT", subPos:"LW",  ovr:87, club:"AC Milan",       nat:"Portugal",   cardType:"special", flag:"🇵🇹", faceUrl:"https://cdn.sofifa.net/players/246/432/25_120.png" },
  { id:33,  name:"F. de Jong",     pos:"MID", subPos:"CM",  ovr:86, club:"Barcelona",      nat:"Netherlands",cardType:"special", flag:"🇳🇱", faceUrl:"https://cdn.sofifa.net/players/240/249/25_120.png" },
  { id:34,  name:"P. Dybala",      pos:"ATT", subPos:"CAM", ovr:87, club:"AS Roma",        nat:"Argentina",  cardType:"special", flag:"🇦🇷", faceUrl:"https://cdn.sofifa.net/players/211/110/25_120.png" },
  { id:35,  name:"K. Benzema",     pos:"ATT", subPos:"ST",  ovr:89, club:"Al-Ittihad",     nat:"France",     cardType:"special", flag:"🇫🇷", faceUrl:"https://cdn.sofifa.net/players/165/153/25_120.png" },
  { id:36,  name:"N. Barella",     pos:"MID", subPos:"CM",  ovr:87, club:"Inter Milan",    nat:"Italy",      cardType:"special", flag:"🇮🇹", faceUrl:"https://cdn.sofifa.net/players/224/336/25_120.png" },
  { id:37,  name:"M. Salah",       pos:"ATT", subPos:"RW",  ovr:89, club:"Liverpool",      nat:"Egypt",      cardType:"special", flag:"🇪🇬", faceUrl:"https://cdn.sofifa.net/players/209/331/25_120.png" },
  { id:38,  name:"Son Heung-min",  pos:"ATT", subPos:"LW",  ovr:87, club:"Tottenham",      nat:"S. Korea",   cardType:"special", flag:"🇰🇷", faceUrl:"https://cdn.sofifa.net/players/200/104/25_120.png" },
  { id:39,  name:"Jamal Musiala",  pos:"MID", subPos:"CAM", ovr:87, club:"Bayern Munich",  nat:"Germany",    cardType:"special", flag:"🇩🇪", faceUrl:"https://cdn.sofifa.net/players/256/630/25_120.png" },
  { id:40,  name:"Florian Wirtz",  pos:"MID", subPos:"CAM", ovr:88, club:"B. Leverkusen",  nat:"Germany",    cardType:"special", flag:"🇩🇪", faceUrl:"https://cdn.sofifa.net/players/256/634/25_120.png" },

  // ── GOLD GKs ───────────────────────────────────────
  { id:41,  name:"T. Courtois",    pos:"GK",  subPos:"GK",  ovr:91, club:"Real Madrid",    nat:"Belgium",    cardType:"gold",    flag:"🇧🇪", faceUrl:"https://cdn.sofifa.net/players/192/119/25_120.png" },
  { id:42,  name:"Alisson",        pos:"GK",  subPos:"GK",  ovr:89, club:"Liverpool",      nat:"Brazil",     cardType:"gold",    flag:"🇧🇷", faceUrl:"https://cdn.sofifa.net/players/212/831/25_120.png" },
  { id:43,  name:"M. ter Stegen",  pos:"GK",  subPos:"GK",  ovr:89, club:"Barcelona",      nat:"Germany",    cardType:"gold",    flag:"🇩🇪", faceUrl:"https://cdn.sofifa.net/players/192/448/25_120.png" },
  { id:44,  name:"E. Martínez",    pos:"GK",  subPos:"GK",  ovr:89, club:"Aston Villa",    nat:"Argentina",  cardType:"gold",    flag:"🇦🇷", faceUrl:"https://cdn.sofifa.net/players/202/652/25_120.png" },
  { id:45,  name:"K. Navas",       pos:"GK",  subPos:"GK",  ovr:85, club:"Free Agent",     nat:"Costa Rica", cardType:"gold",    flag:"🇨🇷", faceUrl:"https://cdn.sofifa.net/players/193/041/25_120.png" },
  { id:46,  name:"M. Neuer",       pos:"GK",  subPos:"GK",  ovr:88, club:"Bayern Munich",  nat:"Germany",    cardType:"gold",    flag:"🇩🇪", faceUrl:"https://cdn.sofifa.net/players/167/495/25_120.png" },
  { id:47,  name:"J. Oblak",       pos:"GK",  subPos:"GK",  ovr:88, club:"Atlético Madrid",nat:"Slovenia",   cardType:"gold",    flag:"🇸🇮", faceUrl:"https://cdn.sofifa.net/players/200/389/25_120.png" },
  { id:48,  name:"G. Donnarumma",  pos:"GK",  subPos:"GK",  ovr:89, club:"PSG",           nat:"Italy",      cardType:"gold",    flag:"🇮🇹", faceUrl:"https://cdn.sofifa.net/players/230/621/25_120.png" },
  { id:49,  name:"M. Maignan",     pos:"GK",  subPos:"GK",  ovr:87, club:"AC Milan",       nat:"France",     cardType:"gold",    flag:"🇫🇷", faceUrl:"https://cdn.sofifa.net/players/220/004/25_120.png" },
  { id:50,  name:"Ederson",        pos:"GK",  subPos:"GK",  ovr:88, club:"Man City",       nat:"Brazil",     cardType:"gold",    flag:"🇧🇷", faceUrl:"https://cdn.sofifa.net/players/210/257/25_120.png" },
  { id:51,  name:"Unai Simón",     pos:"GK",  subPos:"GK",  ovr:86, club:"Athletic Club",  nat:"Spain",      cardType:"gold",    flag:"🇪🇸", faceUrl:"https://cdn.sofifa.net/players/234/187/25_120.png" },
  { id:52,  name:"Y. Sommer",      pos:"GK",  subPos:"GK",  ovr:87, club:"Inter Milan",    nat:"Switzerland",cardType:"gold",    flag:"🇨🇭", faceUrl:"https://cdn.sofifa.net/players/177/683/25_120.png" },
  { id:53,  name:"G. Vicario",     pos:"GK",  subPos:"GK",  ovr:84, club:"Tottenham",      nat:"Italy",      cardType:"gold",    flag:"🇮🇹", faceUrl:"https://cdn.sofifa.net/players/232/909/25_120.png" },
  { id:54,  name:"D. Raya",        pos:"GK",  subPos:"GK",  ovr:85, club:"Arsenal",        nat:"Spain",      cardType:"gold",    flag:"🇪🇸", faceUrl:"https://cdn.sofifa.net/players/215/316/25_120.png" },
  { id:55,  name:"A. Lunin",       pos:"GK",  subPos:"GK",  ovr:81, club:"Real Madrid",    nat:"Ukraine",    cardType:"gold",    flag:"🇺🇦", faceUrl:"https://cdn.sofifa.net/players/242/445/25_120.png" },

  // ── GOLD DEFs ──────────────────────────────────────
  { id:60,  name:"V. van Dijk",    pos:"DEF", subPos:"CB",  ovr:90, club:"Liverpool",      nat:"Netherlands",cardType:"gold",    flag:"🇳🇱", faceUrl:"https://cdn.sofifa.net/players/203/376/25_120.png" },
  { id:61,  name:"K. Rüdiger",     pos:"DEF", subPos:"CB",  ovr:88, club:"Real Madrid",    nat:"Germany",    cardType:"gold",    flag:"🇩🇪", faceUrl:"https://cdn.sofifa.net/players/205/498/25_120.png" },
  { id:62,  name:"W. Saliba",      pos:"DEF", subPos:"CB",  ovr:87, club:"Arsenal",        nat:"France",     cardType:"gold",    flag:"🇫🇷", faceUrl:"https://cdn.sofifa.net/players/243/715/25_120.png" },
  { id:63,  name:"T. Hernández",   pos:"DEF", subPos:"LB",  ovr:87, club:"AC Milan",       nat:"France",     cardType:"gold",    flag:"🇫🇷", faceUrl:"https://cdn.sofifa.net/players/232/656/25_120.png" },
  { id:64,  name:"João Cancelo",   pos:"DEF", subPos:"RB",  ovr:86, club:"Al Hilal",       nat:"Portugal",   cardType:"gold",    flag:"🇵🇹", faceUrl:"https://cdn.sofifa.net/players/210/514/25_120.png" },
  { id:65,  name:"A. Robertson",   pos:"DEF", subPos:"LB",  ovr:85, club:"Liverpool",      nat:"Scotland",   cardType:"gold",    flag:"🏴󠁧󠁢󠁳󠁣󠁴󠁿", faceUrl:"https://cdn.sofifa.net/players/216/267/25_120.png" },
  { id:66,  name:"Dani Carvajal",  pos:"DEF", subPos:"RB",  ovr:86, club:"Real Madrid",    nat:"Spain",      cardType:"gold",    flag:"🇪🇸", faceUrl:"https://cdn.sofifa.net/players/204/963/25_120.png" },
  { id:67,  name:"A. Davies",      pos:"DEF", subPos:"LB",  ovr:84, club:"Bayern Munich",  nat:"Canada",     cardType:"gold",    flag:"🇨🇦", faceUrl:"https://cdn.sofifa.net/players/234/396/25_120.png" },
  { id:68,  name:"B. Pavard",      pos:"DEF", subPos:"CB",  ovr:84, club:"Inter Milan",    nat:"France",     cardType:"gold",    flag:"🇫🇷", faceUrl:"https://cdn.sofifa.net/players/226/851/25_120.png" },
  { id:69,  name:"A. Bastoni",     pos:"DEF", subPos:"CB",  ovr:87, club:"Inter Milan",    nat:"Italy",      cardType:"gold",    flag:"🇮🇹", faceUrl:"https://cdn.sofifa.net/players/237/382/25_120.png" },
  { id:70,  name:"Rúben Dias",     pos:"DEF", subPos:"CB",  ovr:88, club:"Man City",       nat:"Portugal",   cardType:"gold",    flag:"🇵🇹", faceUrl:"https://cdn.sofifa.net/players/239/818/25_120.png" },
  { id:71,  name:"J. Gvardiol",    pos:"DEF", subPos:"CB",  ovr:85, club:"Man City",       nat:"Croatia",    cardType:"gold",    flag:"🇭🇷", faceUrl:"https://cdn.sofifa.net/players/254/980/25_120.png" },
  { id:72,  name:"Marquinhos",     pos:"DEF", subPos:"CB",  ovr:87, club:"PSG",           nat:"Brazil",     cardType:"gold",    flag:"🇧🇷", faceUrl:"https://cdn.sofifa.net/players/207/865/25_120.png" },
  { id:73,  name:"E. Militão",     pos:"DEF", subPos:"CB",  ovr:85, club:"Real Madrid",    nat:"Brazil",     cardType:"gold",    flag:"🇧🇷", faceUrl:"https://cdn.sofifa.net/players/240/130/25_120.png" },
  { id:74,  name:"J. Koundé",      pos:"DEF", subPos:"RB",  ovr:85, club:"Barcelona",      nat:"France",     cardType:"gold",    flag:"🇫🇷", faceUrl:"https://cdn.sofifa.net/players/235/418/25_120.png" },
  { id:75,  name:"R. Araújo",      pos:"DEF", subPos:"CB",  ovr:85, club:"Barcelona",      nat:"Uruguay",    cardType:"gold",    flag:"🇺🇾", faceUrl:"https://cdn.sofifa.net/players/253/163/25_120.png" },
  { id:76,  name:"G. Magalhães",   pos:"DEF", subPos:"CB",  ovr:86, club:"Arsenal",        nat:"Brazil",     cardType:"gold",    flag:"🇧🇷", faceUrl:"https://cdn.sofifa.net/players/237/679/25_120.png" },
  { id:77,  name:"J. Frimpong",    pos:"DEF", subPos:"RB",  ovr:84, club:"B. Leverkusen",  nat:"Netherlands",cardType:"gold",    flag:"🇳🇱", faceUrl:"https://cdn.sofifa.net/players/247/219/25_120.png" },
  { id:78,  name:"Federico Dimarco",pos:"DEF",subPos:"LB", ovr:84, club:"Inter Milan",    nat:"Italy",      cardType:"gold",    flag:"🇮🇹", faceUrl:"https://cdn.sofifa.net/players/220/834/25_120.png" },
  { id:79,  name:"Nuno Mendes",    pos:"DEF", subPos:"LB",  ovr:83, club:"PSG",           nat:"Portugal",   cardType:"gold",    flag:"🇵🇹", faceUrl:"https://cdn.sofifa.net/players/257/570/25_120.png" },
  { id:80,  name:"M. Akanji",      pos:"DEF", subPos:"CB",  ovr:84, club:"Man City",       nat:"Switzerland",cardType:"gold",    flag:"🇨🇭", faceUrl:"https://cdn.sofifa.net/players/229/984/25_120.png" },

  // ── GOLD MIDs ──────────────────────────────────────
  { id:100, name:"K. De Bruyne",   pos:"MID", subPos:"CM",  ovr:90, club:"Man City",       nat:"Belgium",    cardType:"gold",    flag:"🇧🇪", faceUrl:"https://cdn.sofifa.net/players/192/985/25_120.png" },
  { id:101, name:"T. Kroos",       pos:"MID", subPos:"CM",  ovr:89, club:"Real Madrid (I)",nat:"Germany",    cardType:"gold",    flag:"🇩🇪", faceUrl:"https://cdn.sofifa.net/players/182/521/25_120.png" },
  { id:102, name:"F. Valverde",    pos:"MID", subPos:"CM",  ovr:88, club:"Real Madrid",    nat:"Uruguay",    cardType:"gold",    flag:"🇺🇾", faceUrl:"https://cdn.sofifa.net/players/239/053/25_120.png" },
  { id:103, name:"P. Foden",       pos:"MID", subPos:"CAM", ovr:88, club:"Man City",       nat:"England",    cardType:"gold",    flag:"🏴󠁧󠁢󠁥󠁮󠁧󠁿", faceUrl:"https://cdn.sofifa.net/players/237/692/25_120.png" },
  { id:104, name:"D. Rice",        pos:"MID", subPos:"CDM", ovr:87, club:"Arsenal",        nat:"England",    cardType:"gold",    flag:"🏴󠁧󠁢󠁥󠁮󠁧󠁿", faceUrl:"https://cdn.sofifa.net/players/234/378/25_120.png" },
  { id:105, name:"A. Tchouaméni",  pos:"MID", subPos:"CDM", ovr:85, club:"Real Madrid",    nat:"France",     cardType:"gold",    flag:"🇫🇷", faceUrl:"https://cdn.sofifa.net/players/241/637/25_120.png" },
  { id:106, name:"Dani Olmo",      pos:"MID", subPos:"CAM", ovr:86, club:"Barcelona",      nat:"Spain",      cardType:"gold",    flag:"🇪🇸", faceUrl:"https://cdn.sofifa.net/players/230/481/25_120.png" },
  { id:107, name:"L. Modrić",      pos:"MID", subPos:"CM",  ovr:86, club:"Real Madrid",    nat:"Croatia",    cardType:"gold",    flag:"🇭🇷", faceUrl:"https://cdn.sofifa.net/players/177/003/25_120.png" },
  { id:108, name:"B. Fernandes",   pos:"MID", subPos:"CAM", ovr:87, club:"Man Utd",        nat:"Portugal",   cardType:"gold",    flag:"🇵🇹", faceUrl:"https://cdn.sofifa.net/players/212/198/25_120.png" },
  { id:109, name:"Pedri",          pos:"MID", subPos:"CM",  ovr:86, club:"Barcelona",      nat:"Spain",      cardType:"gold",    flag:"🇪🇸", faceUrl:"https://cdn.sofifa.net/players/251/854/25_120.png" },
  { id:110, name:"E. Camavinga",   pos:"MID", subPos:"CM",  ovr:84, club:"Real Madrid",    nat:"France",     cardType:"gold",    flag:"🇫🇷", faceUrl:"https://cdn.sofifa.net/players/248/243/25_120.png" },
  { id:111, name:"Bernardo Silva", pos:"MID", subPos:"CM",  ovr:88, club:"Man City",       nat:"Portugal",   cardType:"gold",    flag:"🇵🇹", faceUrl:"https://cdn.sofifa.net/players/218/667/25_120.png" },
  { id:112, name:"M. Ødegaard",    pos:"MID", subPos:"CAM", ovr:89, club:"Arsenal",        nat:"Norway",     cardType:"gold",    flag:"🇳🇴", faceUrl:"https://cdn.sofifa.net/players/222/492/25_120.png" },
  { id:113, name:"Alexis Mac Allister",pos:"MID",subPos:"CM",ovr:86,club:"Liverpool",      nat:"Argentina",  cardType:"gold",    flag:"🇦🇷", faceUrl:"https://cdn.sofifa.net/players/241/464/25_120.png" },
  { id:114, name:"Enzo Fernández", pos:"MID", subPos:"CM",  ovr:82, club:"Chelsea",        nat:"Argentina",  cardType:"gold",    flag:"🇦🇷", faceUrl:"https://cdn.sofifa.net/players/256/289/25_120.png" },
  { id:115, name:"H. Aouar",       pos:"MID", subPos:"CM",  ovr:80, club:"Al-Ittihad",     nat:"Algeria",    cardType:"gold",    flag:"🇩🇿", faceUrl:"https://cdn.sofifa.net/players/231/677/25_120.png" },
  { id:116, name:"Hakan Çalhanoğlu",pos:"MID",subPos:"CDM", ovr:86, club:"Inter Milan",    nat:"Turkey",     cardType:"gold",    flag:"🇹🇷", faceUrl:"https://cdn.sofifa.net/players/208/574/25_120.png" },
  { id:117, name:"Granit Xhaka",   pos:"MID", subPos:"CDM", ovr:86, club:"B. Leverkusen",  nat:"Switzerland",cardType:"gold",    flag:"🇨🇭", faceUrl:"https://cdn.sofifa.net/players/198/710/25_120.png" },
  { id:118, name:"J. Kimmich",     pos:"MID", subPos:"CDM", ovr:86, club:"Bayern Munich",  nat:"Germany",    cardType:"gold",    flag:"🇩🇪", faceUrl:"https://cdn.sofifa.net/players/212/622/25_120.png" },
  { id:119, name:"João Palhinha",  pos:"MID", subPos:"CDM", ovr:85, club:"Bayern Munich",  nat:"Portugal",   cardType:"gold",    flag:"🇵🇹", faceUrl:"https://cdn.sofifa.net/players/228/702/25_120.png" },

  // ── GOLD ATTs ──────────────────────────────────────
  { id:140, name:"R. Lewandowski", pos:"ATT", subPos:"ST",  ovr:88, club:"Barcelona",      nat:"Poland",     cardType:"gold",    flag:"🇵🇱", faceUrl:"https://cdn.sofifa.net/players/188/545/25_120.png" },
  { id:141, name:"Harry Kane",     pos:"ATT", subPos:"ST",  ovr:90, club:"Bayern Munich",  nat:"England",    cardType:"gold",    flag:"🏴󠁧󠁢󠁥󠁮󠁧󠁿", faceUrl:"https://cdn.sofifa.net/players/202/126/25_120.png" },
  { id:142, name:"A. Griezmann",   pos:"ATT", subPos:"ST",  ovr:88, club:"Atlético Madrid",nat:"France",     cardType:"gold",    flag:"🇫🇷", faceUrl:"https://cdn.sofifa.net/players/194/765/25_120.png" },
  { id:143, name:"L. Suárez",      pos:"ATT", subPos:"ST",  ovr:82, club:"Inter Miami",    nat:"Uruguay",    cardType:"gold",    flag:"🇺🇾", faceUrl:"https://cdn.sofifa.net/players/176/580/25_120.png" },
  { id:144, name:"Bukayo Saka",    pos:"ATT", subPos:"RW",  ovr:87, club:"Arsenal",        nat:"England",    cardType:"gold",    flag:"🏴󠁧󠁢󠁥󠁮󠁧󠁿", faceUrl:"https://cdn.sofifa.net/players/246/669/25_120.png" },
  { id:145, name:"L. Díaz",        pos:"ATT", subPos:"LW",  ovr:84, club:"Liverpool",      nat:"Colombia",   cardType:"gold",    flag:"🇨🇴", faceUrl:"https://cdn.sofifa.net/players/241/084/25_120.png" },
  { id:146, name:"O. Dembélé",     pos:"ATT", subPos:"RW",  ovr:86, club:"PSG",           nat:"France",     cardType:"gold",    flag:"🇫🇷", faceUrl:"https://cdn.sofifa.net/players/231/443/25_120.png" },
  { id:147, name:"V. Osimhen",     pos:"ATT", subPos:"ST",  ovr:87, club:"Galatasaray",    nat:"Nigeria",    cardType:"gold",    flag:"🇳🇬", faceUrl:"https://cdn.sofifa.net/players/232/293/25_120.png" },
  { id:148, name:"L. Martínez",    pos:"ATT", subPos:"ST",  ovr:89, club:"Inter Milan",    nat:"Argentina",  cardType:"gold",    flag:"🇦🇷", faceUrl:"https://cdn.sofifa.net/players/231/478/25_120.png" },
  { id:149, name:"K. Havertz",     pos:"ATT", subPos:"ST",  ovr:83, club:"Arsenal",        nat:"Germany",    cardType:"gold",    flag:"🇩🇪", faceUrl:"https://cdn.sofifa.net/players/235/790/25_120.png" },
  { id:150, name:"D. Núñez",       pos:"ATT", subPos:"ST",  ovr:82, club:"Liverpool",      nat:"Uruguay",    cardType:"gold",    flag:"🇺🇾", faceUrl:"https://cdn.sofifa.net/players/251/157/25_120.png" },
  { id:151, name:"G. Martinelli",  pos:"ATT", subPos:"LW",  ovr:83, club:"Arsenal",        nat:"Brazil",     cardType:"gold",    flag:"🇧🇷", faceUrl:"https://cdn.sofifa.net/players/251/570/25_120.png" },
  { id:152, name:"K. Kvaratskhelia",pos:"ATT",subPos:"LW",  ovr:85, club:"Napoli",         nat:"Georgia",    cardType:"gold",    flag:"🇬🇪", faceUrl:"https://cdn.sofifa.net/players/247/635/25_120.png" },
  { id:153, name:"Neymar Jr.",     pos:"ATT", subPos:"LW",  ovr:87, club:"Al Hilal",       nat:"Brazil",     cardType:"gold",    flag:"🇧🇷", faceUrl:"https://cdn.sofifa.net/players/190/871/25_120.png" },
  { id:154, name:"Raphinha",       pos:"ATT", subPos:"RW",  ovr:84, club:"Barcelona",      nat:"Brazil",     cardType:"gold",    flag:"🇧🇷", faceUrl:"https://cdn.sofifa.net/players/233/419/25_120.png" },
  { id:155, name:"Cole Palmer",    pos:"ATT", subPos:"RW",  ovr:85, club:"Chelsea",        nat:"England",    cardType:"gold",    flag:"🏴󠁧󠁢󠁥󠁮󠁧󠁿", faceUrl:"https://cdn.sofifa.net/players/257/530/25_120.png" },

  // ── EXPANSION PLAYERS (150+ NEW STAR PLAYERS TO REACH 350+) ───────────────
  // GKs (NEW)
  { id:301, name:"G. Mamardashvili",pos:"GK", subPos:"GK",  ovr:85, club:"Valencia",      nat:"Georgia",    cardType:"gold",    flag:"🇬🇪", faceUrl:"https://cdn.sofifa.net/players/253/639/25_120.png" },
  { id:302, name:"G. Kobel",       pos:"GK",  subPos:"GK",  ovr:88, club:"Dortmund",      nat:"Switzerland",cardType:"gold",    flag:"🇨🇭", faceUrl:"https://cdn.sofifa.net/players/231/450/25_120.png" },
  { id:303, name:"Álvaro Valles",  pos:"GK",  subPos:"GK",  ovr:81, club:"Las Palmas",    nat:"Spain",      cardType:"silver",  flag:"🇪🇸", faceUrl:"https://cdn.sofifa.net/players/251/875/25_120.png" },
  { id:304, name:"M. Carnesecchi", pos:"GK",  subPos:"GK",  ovr:81, club:"Atalanta",      nat:"Italy",      cardType:"silver",  flag:"🇮🇹", faceUrl:"https://cdn.sofifa.net/players/244/676/25_120.png" },
  { id:305, name:"A. Meret",       pos:"GK",  subPos:"GK",  ovr:82, club:"Napoli",        nat:"Italy",      cardType:"silver",  flag:"🇮🇹", faceUrl:"https://cdn.sofifa.net/players/225/951/25_120.png" },
  { id:306, name:"B. Samba",       pos:"GK",  subPos:"GK",  ovr:81, club:"RC Lens",       nat:"France",     cardType:"silver",  flag:"🇫🇷", faceUrl:"https://cdn.sofifa.net/players/213/698/25_120.png" },
  { id:307, name:"K. Casteels",    pos:"GK",  subPos:"GK",  ovr:82, club:"Al Qadsiah",    nat:"Belgium",    cardType:"silver",  flag:"🇧🇪", faceUrl:"https://cdn.sofifa.net/players/192/635/25_120.png" },
  { id:308, name:"E. Mendy",       pos:"GK",  subPos:"GK",  ovr:80, club:"Al-Ahli",       nat:"Senegal",    cardType:"silver",  flag:"🇸🇳", faceUrl:"https://cdn.sofifa.net/players/240/918/25_120.png" },
  { id:309, name:"J. Pickford",    pos:"GK",  subPos:"GK",  ovr:83, club:"Everton",       nat:"England",    cardType:"gold",    flag:"🏴󠁧󠁢󠁥󠁮󠁧󠁿", faceUrl:"https://cdn.sofifa.net/players/204/935/25_120.png" },
  { id:310, name:"N. Pope",        pos:"GK",  subPos:"GK",  ovr:81, club:"Newcastle",     nat:"England",    cardType:"silver",  flag:"🏴󠁧󠁢󠁥󠁮󠁧󠁿", faceUrl:"https://cdn.sofifa.net/players/209/244/25_120.png" },
  { id:311, name:"L. Hrádecký",    pos:"GK",  subPos:"GK",  ovr:85, club:"B. Leverkusen", nat:"Finland",    cardType:"gold",    flag:"🇫🇮", faceUrl:"https://cdn.sofifa.net/players/200/212/25_120.png" },
  { id:312, name:"W. Benítez",     pos:"GK",  subPos:"GK",  ovr:81, club:"PSV",           nat:"Argentina",  cardType:"silver",  flag:"🇦🇷", faceUrl:"https://cdn.sofifa.net/players/228/693/25_120.png" },
  { id:313, name:"Ivan Provedel",  pos:"GK",  subPos:"GK",  ovr:82, club:"Lazio",         nat:"Italy",      cardType:"silver",  flag:"🇮🇹", faceUrl:"https://cdn.sofifa.net/players/214/431/25_120.png" },
  { id:314, name:"S. Ortega",      pos:"GK",  subPos:"GK",  ovr:80, club:"Man City",      nat:"Germany",    cardType:"silver",  flag:"🇩🇪", faceUrl:"https://cdn.sofifa.net/players/206/001/25_120.png" },
  { id:315, name:"B. Verbruggen",  pos:"GK",  subPos:"GK",  ovr:78, club:"Brighton",      nat:"Netherlands",cardType:"silver",  flag:"🇳🇱", faceUrl:"https://cdn.sofifa.net/players/258/587/25_120.png" },

  // DEFs (NEW)
  { id:320, name:"Pau Torres",     pos:"DEF", subPos:"CB",  ovr:83, club:"Aston Villa",   nat:"Spain",      cardType:"gold",    flag:"🇪🇸", faceUrl:"https://cdn.sofifa.net/players/234/062/25_120.png" },
  { id:321, name:"M. de Ligt",     pos:"DEF", subPos:"CB",  ovr:84, club:"Man Utd",       nat:"Netherlands",cardType:"gold",    flag:"🇳🇱", faceUrl:"https://cdn.sofifa.net/players/235/243/25_120.png" },
  { id:322, name:"Lisandro Martínez",pos:"DEF",subPos:"CB", ovr:84, club:"Man Utd",       nat:"Argentina",  cardType:"gold",    flag:"🇦🇷", faceUrl:"https://cdn.sofifa.net/players/239/301/25_120.png" },
  { id:323, name:"N. Schlotterbeck",pos:"DEF",subPos:"CB", ovr:85, club:"Dortmund",      nat:"Germany",    cardType:"gold",    flag:"🇩🇪", faceUrl:"https://cdn.sofifa.net/players/244/651/25_120.png" },
  { id:324, name:"W. Orban",       pos:"DEF", subPos:"CB",  ovr:83, club:"RB Leipzig",    nat:"Hungary",    cardType:"gold",    flag:"🇭🇺", faceUrl:"https://cdn.sofifa.net/players/204/636/25_120.png" },
  { id:325, name:"Piero Hincapié", pos:"DEF", subPos:"LB",  ovr:81, club:"B. Leverkusen", nat:"Ecuador",    cardType:"silver",  flag:"🇪🇨", faceUrl:"https://cdn.sofifa.net/players/256/966/25_120.png" },
  { id:326, name:"Jonathan Tah",   pos:"DEF", subPos:"CB",  ovr:86, club:"B. Leverkusen", nat:"Germany",    cardType:"gold",    flag:"🇩🇪", faceUrl:"https://cdn.sofifa.net/players/215/333/25_120.png" },
  { id:327, name:"Destiny Udogie", pos:"DEF", subPos:"LB",  ovr:82, club:"Tottenham",     nat:"Italy",      cardType:"silver",  flag:"🇮🇹", faceUrl:"https://cdn.sofifa.net/players/258/117/25_120.png" },
  { id:328, name:"Pedro Porro",    pos:"DEF", subPos:"RB",  ovr:83, club:"Tottenham",     nat:"Spain",      cardType:"gold",    flag:"🇪🇸", faceUrl:"https://cdn.sofifa.net/players/246/381/25_120.png" },
  { id:329, name:"T. Livramento",  pos:"DEF", subPos:"RB",  ovr:78, club:"Newcastle",     nat:"England",    cardType:"silver",  flag:"🏴󠁧󠁢󠁥󠁮󠁧󠁿", faceUrl:"https://cdn.sofifa.net/players/254/676/25_120.png" },
  { id:330, name:"M. Cucurella",   pos:"DEF", subPos:"LB",  ovr:82, club:"Chelsea",       nat:"Spain",      cardType:"silver",  flag:"🇪🇸", faceUrl:"https://cdn.sofifa.net/players/239/651/25_120.png" },
  { id:331, name:"L. Geertruida",  pos:"DEF", subPos:"RB",  ovr:80, club:"RB Leipzig",    nat:"Netherlands",cardType:"silver",  flag:"🇳🇱", faceUrl:"https://cdn.sofifa.net/players/243/951/25_120.png" },
  { id:332, name:"Nathan Aké",     pos:"DEF", subPos:"CB",  ovr:84, club:"Man City",      nat:"Netherlands",cardType:"gold",    flag:"🇳🇱", faceUrl:"https://cdn.sofifa.net/players/208/920/25_120.png" },
  { id:333, name:"J. Laporte",     pos:"DEF", subPos:"CB",  ovr:83, club:"Al Nassr",      nat:"Spain",      cardType:"gold",    flag:"🇪🇸", faceUrl:"https://cdn.sofifa.net/players/212/219/25_120.png" },
  { id:334, name:"Kalidou Koulibaly",pos:"DEF",subPos:"CB",ovr:84, club:"Al Hilal",      nat:"Senegal",    cardType:"gold",    flag:"🇸🇳", faceUrl:"https://cdn.sofifa.net/players/201/047/25_120.png" },
  { id:335, name:"N. Mazraoui",    pos:"DEF", subPos:"RB",  ovr:81, club:"Man Utd",       nat:"Morocco",    cardType:"silver",  flag:"🇲🇦", faceUrl:"https://cdn.sofifa.net/players/236/401/25_120.png" },
  { id:336, name:"Danilo",         pos:"DEF", subPos:"CB",  ovr:82, club:"Juventus",      nat:"Brazil",     cardType:"silver",  flag:"🇧🇷", faceUrl:"https://cdn.sofifa.net/players/199/304/25_120.png" },
  { id:337, name:"G. Di Lorenzo",  pos:"DEF", subPos:"RB",  ovr:83, club:"Napoli",        nat:"Italy",      cardType:"silver",  flag:"🇮🇹", faceUrl:"https://cdn.sofifa.net/players/236/635/25_120.png" },
  { id:338, name:"A. Rrahmani",    pos:"DEF", subPos:"CB",  ovr:81, club:"Napoli",        nat:"Kosovo",     cardType:"silver",  flag:"🇽🇰", faceUrl:"https://cdn.sofifa.net/players/228/341/25_120.png" },
  { id:339, name:"D. Hancko",      pos:"DEF", subPos:"CB",  ovr:82, club:"Feyenoord",     nat:"Slovakia",   cardType:"silver",  flag:"🇸🇰", faceUrl:"https://cdn.sofifa.net/players/241/688/25_120.png" },
  { id:340, name:"S. van de Ven",  pos:"DEF", subPos:"CB",  ovr:82, club:"Tottenham",     nat:"Netherlands",cardType:"silver",  flag:"🇳🇱", faceUrl:"https://cdn.sofifa.net/players/258/364/25_120.png" },
  { id:341, name:"Riccardo Calafiori",pos:"DEF",subPos:"CB",ovr:81,club:"Arsenal",        nat:"Italy",      cardType:"silver",  flag:"🇮🇹", faceUrl:"https://cdn.sofifa.net/players/252/631/25_120.png" },
  { id:342, name:"Ian Maatsen",    pos:"DEF", subPos:"LB",  ovr:79, club:"Aston Villa",   nat:"Netherlands",cardType:"silver",  flag:"🇳🇱", faceUrl:"https://cdn.sofifa.net/players/251/913/25_120.png" },
  { id:343, name:"J. Tarkowski",   pos:"DEF", subPos:"CB",  ovr:81, club:"Everton",       nat:"England",    cardType:"silver",  flag:"🏴󠁧󠁢󠁥󠁮󠁧󠁿", faceUrl:"https://cdn.sofifa.net/players/210/637/25_120.png" },
  { id:344, name:"E. Konsa",       pos:"DEF", subPos:"CB",  ovr:82, club:"Aston Villa",   nat:"England",    cardType:"silver",  flag:"🏴󠁧󠁢󠁥󠁮󠁧󠁿", faceUrl:"https://cdn.sofifa.net/players/233/639/25_120.png" },
  { id:345, name:"T. Adarabioyo",  pos:"DEF", subPos:"CB",  ovr:78, club:"Chelsea",       nat:"England",    cardType:"silver",  flag:"🏴󠁧󠁢󠁥󠁮󠁧󠁿", faceUrl:"https://cdn.sofifa.net/players/225/638/25_120.png" },

  // MIDs (NEW)
  { id:350, name:"Teun Koopmeiners",pos:"MID",subPos:"CM",  ovr:83, club:"Juventus",      nat:"Netherlands",cardType:"gold",    flag:"🇳🇱", faceUrl:"https://cdn.sofifa.net/players/238/636/25_120.png" },
  { id:351, name:"Douglas Luiz",   pos:"MID", subPos:"CM",  ovr:83, club:"Juventus",      nat:"Brazil",     cardType:"gold",    flag:"🇧🇷", faceUrl:"https://cdn.sofifa.net/players/236/243/25_120.png" },
  { id:352, name:"Bruno Guimarães",pos:"MID", subPos:"CDM", ovr:85, club:"Newcastle",     nat:"Brazil",     cardType:"gold",    flag:"🇧🇷", faceUrl:"https://cdn.sofifa.net/players/247/384/25_120.png" },
  { id:353, name:"Sandro Tonali",  pos:"MID", subPos:"CDM", ovr:85, club:"Newcastle",     nat:"Italy",      cardType:"gold",    flag:"🇮🇹", faceUrl:"https://cdn.sofifa.net/players/241/096/25_120.png" },
  { id:354, name:"L. Paquetá",     pos:"MID", subPos:"CAM", ovr:82, club:"West Ham",      nat:"Brazil",     cardType:"silver",  flag:"🇧🇷", faceUrl:"https://cdn.sofifa.net/players/233/941/25_120.png" },
  { id:355, name:"E. Eze",         pos:"MID", subPos:"CAM", ovr:82, club:"Crystal Palace",nat:"England",    cardType:"silver",  flag:"🏴󠁧󠁢󠁥󠁮󠁧󠁿", faceUrl:"https://cdn.sofifa.net/players/237/981/25_120.png" },
  { id:356, name:"M. Kudus",       pos:"MID", subPos:"CAM", ovr:83, club:"West Ham",      nat:"Ghana",      cardType:"silver",  flag:"🇬🇭", faceUrl:"https://cdn.sofifa.net/players/245/985/25_120.png" },
  { id:357, name:"K. Laimer",      pos:"MID", subPos:"CDM", ovr:83, club:"Bayern Munich",  nat:"Austria",    cardType:"silver",  flag:"🇦🇹", faceUrl:"https://cdn.sofifa.net/players/228/639/25_120.png" },
  { id:358, name:"Xavi Simons",    pos:"MID", subPos:"CAM", ovr:84, club:"RB Leipzig",    nat:"Netherlands",cardType:"gold",    flag:"🇳🇱", faceUrl:"https://cdn.sofifa.net/players/256/635/25_120.png" },
  { id:359, name:"M. Merino",      pos:"MID", subPos:"CM",  ovr:84, club:"Arsenal",        nat:"Spain",      cardType:"gold",    flag:"🇪🇸", faceUrl:"https://cdn.sofifa.net/players/226/639/25_120.png" },
  { id:360, name:"M. Zubimendi",   pos:"MID", subPos:"CDM", ovr:83, club:"Real Sociedad", nat:"Spain",      cardType:"silver",  flag:"🇪🇸", faceUrl:"https://cdn.sofifa.net/players/244/951/25_120.png" },
  { id:361, name:"Álex Baena",     pos:"MID", subPos:"CAM", ovr:82, club:"Villarreal",    nat:"Spain",      cardType:"silver",  flag:"🇪🇸", faceUrl:"https://cdn.sofifa.net/players/251/339/25_120.png" },
  { id:362, name:"P. Højbjerg",    pos:"MID", subPos:"CDM", ovr:82, club:"Marseille",     nat:"Denmark",    cardType:"silver",  flag:"🇩🇰", faceUrl:"https://cdn.sofifa.net/players/213/639/25_120.png" },
  { id:363, name:"Adrien Rabiot",  pos:"MID", subPos:"CM",  ovr:83, club:"Marseille",     nat:"France",     cardType:"silver",  flag:"🇫🇷", faceUrl:"https://cdn.sofifa.net/players/210/339/25_120.png" },
  { id:364, name:"M. Locatelli",   pos:"MID", subPos:"CDM", ovr:83, club:"Juventus",      nat:"Italy",      cardType:"silver",  flag:"🇮🇹", faceUrl:"https://cdn.sofifa.net/players/230/639/25_120.png" },
  { id:365, name:"P. Zieliński",   pos:"MID", subPos:"CM",  ovr:83, club:"Inter Milan",    nat:"Poland",     cardType:"silver",  flag:"🇵🇱", faceUrl:"https://cdn.sofifa.net/players/213/941/25_120.png" },
  { id:366, name:"Mattéo Guendouzi",pos:"MID",subPos:"CM",  ovr:81, club:"Lazio",          nat:"France",     cardType:"silver",  flag:"🇫🇷", faceUrl:"https://cdn.sofifa.net/players/234/941/25_120.png" },
  { id:367, name:"S. Lobotka",     pos:"MID", subPos:"CDM", ovr:83, club:"Napoli",        nat:"Slovakia",   cardType:"silver",  flag:"🇸🇰", faceUrl:"https://cdn.sofifa.net/players/229/339/25_120.png" },
  { id:368, name:"André-Frank Zambo Anguissa",pos:"MID",subPos:"CM",ovr:82,club:"Napoli",  nat:"Cameroon",   cardType:"silver",  flag:"🇨🇲", faceUrl:"https://cdn.sofifa.net/players/227/639/25_120.png" },
  { id:369, name:"João Neves",    pos:"MID", subPos:"CM",  ovr:81, club:"PSG",           nat:"Portugal",   cardType:"silver",  flag:"🇵🇹", faceUrl:"https://cdn.sofifa.net/players/271/339/25_120.png" },
  { id:370, name:"Vitinha",        pos:"MID", subPos:"CM",  ovr:85, club:"PSG",           nat:"Portugal",   cardType:"gold",    flag:"🇵🇹", faceUrl:"https://cdn.sofifa.net/players/252/639/25_120.png" },
  { id:371, name:"Warren Zaïre-Emery",pos:"MID",subPos:"CM",ovr:81,club:"PSG",          nat:"France",     cardType:"silver",  flag:"🇫🇷", faceUrl:"https://cdn.sofifa.net/players/270/860/25_120.png" },
  { id:372, name:"K. Thuram",      pos:"MID", subPos:"CM",  ovr:80, club:"Juventus",      nat:"France",     cardType:"silver",  flag:"🇫🇷", faceUrl:"https://cdn.sofifa.net/players/248/941/25_120.png" },
  { id:373, name:"R. Bentancur",   pos:"MID", subPos:"CM",  ovr:81, club:"Tottenham",     nat:"Uruguay",    cardType:"silver",  flag:"🇺🇾", faceUrl:"https://cdn.sofifa.net/players/232/339/25_120.png" },

  // ATTs (NEW)
  { id:380, name:"Marcus Thuram",  pos:"ATT", subPos:"ST",  ovr:84, club:"Inter Milan",    nat:"France",     cardType:"gold",    flag:"🇫🇷", faceUrl:"https://cdn.sofifa.net/players/225/941/25_120.png" },
  { id:381, name:"Nico Williams",  pos:"ATT", subPos:"LW",  ovr:85, club:"Athletic Club",  nat:"Spain",      cardType:"gold",    flag:"🇪🇸", faceUrl:"https://cdn.sofifa.net/players/259/339/25_120.png" },
  { id:382, name:"Takefusa Kubo",  pos:"ATT", subPos:"RW",  ovr:82, club:"Real Sociedad", nat:"Japan",      cardType:"silver",  flag:"🇯🇵", faceUrl:"https://cdn.sofifa.net/players/244/635/25_120.png" },
  { id:383, name:"Viktor Gyökeres",pos:"ATT", subPos:"ST",  ovr:84, club:"Sporting CP",    nat:"Sweden",     cardType:"gold",    flag:"🇸🇪", faceUrl:"https://cdn.sofifa.net/players/242/339/25_120.png" },
  { id:384, name:"Lois Openda",    pos:"ATT", subPos:"ST",  ovr:84, club:"RB Leipzig",    nat:"Belgium",    cardType:"gold",    flag:"🇧🇪", faceUrl:"https://cdn.sofifa.net/players/245/339/25_120.png" },
  { id:385, name:"Serhou Guirassy",pos:"ATT", subPos:"ST",  ovr:84, club:"Dortmund",      nat:"Guinea",     cardType:"gold",    flag:"🇬🇳", faceUrl:"https://cdn.sofifa.net/players/224/941/25_120.png" },
  { id:386, name:"Benjamin Šeško",pos:"ATT", subPos:"ST",  ovr:82, club:"RB Leipzig",    nat:"Slovenia",   cardType:"silver",  flag:"🇸🇮", faceUrl:"https://cdn.sofifa.net/players/257/339/25_120.png" },
  { id:387, name:"Endrick",        pos:"ATT", subPos:"ST",  ovr:77, club:"Real Madrid",    nat:"Brazil",     cardType:"silver",  flag:"🇧🇷", faceUrl:"https://cdn.sofifa.net/players/275/727/25_120.png" },
  { id:388, name:"Arda Güler",     pos:"MID", subPos:"CAM", ovr:78, club:"Real Madrid",    nat:"Turkey",     cardType:"silver",  flag:"🇹🇷", faceUrl:"https://cdn.sofifa.net/players/268/328/25_120.png" },
  { id:389, name:"Savinho",        pos:"ATT", subPos:"RW",  ovr:82, club:"Man City",       nat:"Brazil",     cardType:"silver",  flag:"🇧🇷", faceUrl:"https://cdn.sofifa.net/players/260/024/25_120.png" },
  { id:390, name:"Jérémy Doku",    pos:"ATT", subPos:"LW",  ovr:81, club:"Man City",       nat:"Belgium",    cardType:"silver",  flag:"🇧🇪", faceUrl:"https://cdn.sofifa.net/players/246/186/25_120.png" },
  { id:391, name:"Anthony Gordon", pos:"ATT", subPos:"LW",  ovr:82, club:"Newcastle",     nat:"England",    cardType:"silver",  flag:"🏴󠁧󠁢󠁥󠁮󠁧󠁿", faceUrl:"https://cdn.sofifa.net/players/246/187/25_120.png" },
  { id:392, name:"Jarrod Bowen",   pos:"ATT", subPos:"RW",  ovr:83, club:"West Ham",      nat:"England",    cardType:"silver",  flag:"🏴󠁧󠁢󠁥󠁮󠁧󠁿", faceUrl:"https://cdn.sofifa.net/players/228/092/25_120.png" },
  { id:393, name:"Bryan Mbeumo",   pos:"ATT", subPos:"RW",  ovr:81, club:"Brentford",     nat:"Cameroon",   cardType:"silver",  flag:"🇨🇲", faceUrl:"https://cdn.sofifa.net/players/244/339/25_120.png" },
  { id:394, name:"Dominic Solanke",pos:"ATT", subPos:"ST",  ovr:81, club:"Tottenham",     nat:"England",    cardType:"silver",  flag:"🏴󠁧󠁢󠁥󠁮󠁧󠁿", faceUrl:"https://cdn.sofifa.net/players/220/785/25_120.png" },
  { id:395, name:"Ollie Watkins",  pos:"ATT", subPos:"ST",  ovr:85, club:"Aston Villa",   nat:"England",    cardType:"gold",    flag:"🏴󠁧󠁢󠁥󠁮󠁧󠁿", faceUrl:"https://cdn.sofifa.net/players/234/519/25_120.png" },
  { id:396, name:"Alexander Isak", pos:"ATT", subPos:"ST",  ovr:85, club:"Newcastle",     nat:"Sweden",     cardType:"gold",    flag:"🇸🇪", faceUrl:"https://cdn.sofifa.net/players/233/731/25_120.png" },
  { id:397, name:"Mateo Retegui",  pos:"ATT", subPos:"ST",  ovr:81, club:"Atalanta",      nat:"Italy",      cardType:"silver",  flag:"🇮🇹", faceUrl:"https://cdn.sofifa.net/players/250/339/25_120.png" },
  { id:398, name:"Ademola Lookman",pos:"ATT", subPos:"LW",  ovr:84, club:"Atalanta",      nat:"Nigeria",    cardType:"gold",    flag:"🇳🇬", faceUrl:"https://cdn.sofifa.net/players/233/339/25_120.png" },
  { id:399, name:"Gianluca Scamacca",pos:"ATT",subPos:"ST", ovr:82, club:"Atalanta",      nat:"Italy",      cardType:"silver",  flag:"🇮🇹", faceUrl:"https://cdn.sofifa.net/players/236/941/25_120.png" },
  { id:400, name:"Kaoru Mitoma",   pos:"ATT", subPos:"LW",  ovr:81, club:"Brighton",      nat:"Japan",      cardType:"silver",  flag:"🇯🇵", faceUrl:"https://cdn.sofifa.net/players/258/587/25_120.png" },
];

// Position categories helper
export const POS_MAP = {
  GK:  'GK',
  DEF: 'DEF',
  MID: 'MID',
  ATT: 'ATT',
};

// Return a shuffled copy of the player pool
export function buildPlayerPool() {
  return [...PLAYERS].sort(() => Math.random() - 0.5);
}
